/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(){function k(a){chrome.windows.getAll({populate:!0},function(c){c.forEach(function(c){c.tabs.forEach(function(c){"init"===a?chrome.tabs.executeScript(c.id,{file:"init.js"},function(a){chrome.runtime.lastError&&(document.documentElement.dataset.e=1)}):chrome.tabs.sendMessage(c.id,a,function(a){chrome.runtime.lastError&&(document.documentElement.dataset.e=1)})})})})}function p(){chrome.webRequest.onBeforeRequest.addListener(r,{urls:["*://www.youtube.com/get_*roll_info*","*://www.youtube.com/get_video_*"]},
["blocking"]);chrome.tabs.onUpdated.addListener(t);chrome.tabs.onRemoved.addListener(u);l=!0}function v(){chrome.webNavigation.onBeforeNavigate.removeListener(m);Object.keys(d).forEach(function(a){delete d[a]});Object.keys(f).forEach(function(a){delete f[a]});Object.keys(g).forEach(function(a){delete g[a]});h()}function w(){chrome.windows.getAll({populate:!0},function(a){a.forEach(function(a){a.tabs.forEach(function(a){/^https:\/\/www\.youtube\.com\/watch/.test(a.url)&&(d[a.id]="");/^https:\/\/www\.youtube\.com\/embed/.test(a.url)&&
(f[a.id]="");/^https:\/\/www\.youtube\.com/.test(a.url)&&(g[a.id]="")})})})}function h(){1>Object.keys(d).length&&1>Object.keys(f).length&&1>Object.keys(g).length&&l&&(chrome.webRequest.onBeforeRequest.removeListener(r),chrome.tabs.onUpdated.removeListener(t),chrome.tabs.onRemoved.removeListener(u),l=!1)}function t(a,c,b){!d.hasOwnProperty(a)&&/^https:\/\/www\.youtube\.com\/watch/.test(b.url)?d[a]="":c.status&&"complete"===c.status&&d.hasOwnProperty(a)&&!/^https:\/\/www\.youtube\.com\/watch/.test(b.url)&&
(delete d[a],h());!f.hasOwnProperty(a)&&/^https:\/\/www\.youtube\.com\/embed/.test(b.url)?f[a]="":c.status&&"complete"===c.status&&f.hasOwnProperty(a)&&!/^https:\/\/www\.youtube\.com\/embed/.test(b.url)&&(delete f[a],h());!g.hasOwnProperty(a)&&/^https:\/\/www\.youtube\.com/.test(b.url)?g[a]="":c.status&&"complete"===c.status&&g.hasOwnProperty(a)&&!/^https:\/\/www\.youtube\.com/.test(b.url)&&(delete g[a],h())}function u(a){d.hasOwnProperty(a)&&(delete d[a],h());f.hasOwnProperty(a)&&(delete f[a],h());
g.hasOwnProperty(a)&&(delete g[a],h())}function r(a){return{cancel:d.hasOwnProperty(a.tabId)&&0>a.url.indexOf("el=detailpage")?!0:f.hasOwnProperty(a.tabId)&&0>a.url.indexOf("el=embedded")?!0:!1}}function m(a){l||(/^https:\/\/www\.youtube\.com\/watch/.test(a.url)?d[a.tabId]="":/^https:\/\/www\.youtube\.com\/embed/.test(a.url)&&(f[a.tabId]=""),g[a.tabId]="",p())}chrome.runtime.onInstalled.addListener(function(a){"install"===a.reason&&(chrome.tabs.create({url:"options.html",active:!1}),chrome.tabs.create({url:"https://www.mrfdev.com/event?n=install&b=chrome&e=enhancer-for-youtube&v="+
chrome.runtime.getManifest().version,active:!0}),n=Date.now(),chrome.storage.local.set({date:n}),k("init"));"update"===a.reason&&k("init")});chrome.runtime.setUninstallURL("https://www.mrfdev.com/event?n=uninstall&b=chrome&e=enhancer-for-youtube&v="+chrome.runtime.getManifest().version+"&d="+n+"-"+Date.now());chrome.runtime.onMessage.addListener(function(a,c,d){var e=a.enhancerforyoutube;if("pause-videos"===e)k({message:"enhancerforyoutube:pause-video"});else if("detach"===e)chrome.windows.create({url:"https://www.youtube.com/detached_player/"+
a.params,type:"popup",height:345,width:560,incognito:a.incognito,focused:!0},function(a){chrome.windows.update(a.id,{drawAttention:!0})});else if("set-cookie"===e)chrome.cookies.set({url:a.url,name:a.name,value:a.value,domain:".youtube.com",path:"/",expirationDate:Math.floor(Date.now()/1E3)+31556926});else if("custom-theme"===e)chrome.storage.local.get({customtheme:""},function(a){chrome.tabs.sendMessage(c.tab.id,{message:"enhancerforyoutube:custom-theme",customtheme:a.customtheme})});else if("custom-script"===
e)chrome.storage.local.get({script:""},function(a){chrome.tabs.sendMessage(c.tab.id,{message:"enhancerforyoutube:custom-script",script:a.script})});else if("always-on-top"===e)chrome.tabs.create({url:"https://www.mrfdev.com/always-on-top",active:!0},function(a){chrome.tabs.executeScript(a.id,{code:"window.scrollTo(0, 100)",runAt:"document_end"})});else if("keyboard-shortcuts"===e)chrome.tabs.create({url:"https://www.mrfdev.com/youtube-keyboard-shortcuts",active:!0},function(a){chrome.tabs.executeScript(a.id,
{code:"window.scrollTo(0, 100)",runAt:"document_end"})});else if("show-options"===e)chrome.runtime.openOptionsPage();else if("content.js"===e)chrome.tabs.executeScript(c.tab.id,{file:"content.js"});else if("filters"===e)chrome.tabs.executeScript(c.tab.id,{file:"filters.js"});else if("show-message"===e)chrome.storage.local.set({message:!1},function(){chrome.tabs.create({url:"message.html",active:!0})});else{if("permissions-granted"===e)return b.permissions=!0,b.removeads&&(chrome.webNavigation.onBeforeNavigate.addListener(m,
q),w(),p()),d({response:"granted"}),!0;if("permissions-revoked"===e)return b.permissions=!1,v(),d({response:"revoked"}),!0}});chrome.storage.onChanged.addListener(function(a,c){for(key in a)"undefined"!==typeof a[key].newValue&&("script"!==key&&k({message:"enhancerforyoutube:preference-changed",name:key,value:a[key].newValue}),"removeads"===key&&(b.removeads=a[key].newValue,b.permissions&&b.removeads?(chrome.webNavigation.onBeforeNavigate.addListener(m,q),w(),p()):!b.removeads&&l&&v()))});chrome.commands.onCommand.addListener(function(a){k({message:"enhancerforyoutube:keyboard-shortcut",
command:a})});chrome.browserAction.onClicked.addListener(function(a){chrome.runtime.openOptionsPage()});var n,d={},g={},f={},q={url:[{hostEquals:"www.youtube.com"}]},b={date:Date.now(),permissions:!1,removeads:!1,theatermode:!1,visitor_info1_live:""},l;chrome.storage.local.get(b,function(a){b=a;n=b.date;b.permissions&&b.removeads&&chrome.webNavigation.onBeforeNavigate.addListener(m,q);chrome.cookies.set({url:"https://www.youtube.com/watch",name:"wide",value:b.theatermode?"1":"0",domain:".youtube.com",
path:"/",expirationDate:Math.floor(Date.now()/1E3)+31556926});chrome.cookies.get({url:"https://www.youtube.com",name:"VISITOR_INFO1_LIVE"},function(a){a&&a.value!==b.visitor_info1_live&&chrome.storage.local.set({visitor_info1_live:a.value})})})})();