/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
chrome.storage.local.get({autopausevideos:!0,controlvolume:!1,controlvolumemousebutton:!1,defaultvolume:!1,quality1:"hd1080",overridespeeds:!0,pauseforegroundtab:!1,pausevideos:!0,removeads:!1,removeannotations:!1,reversemousewheeldirection:!1,selectquality:!1,speed:1,speedvariation:.1,volume:50,volumevariation:5},function(v){var f=document.createElement("script");f.textContent="("+function(a){function q(b,d){try{if(Number.isFinite(d.duration)&&7<b.getDuration()-d.duration){var h=b.querySelector("button.ytp-ad-skip-button");
h?h.click():(d.currentTime=d.duration-.5,setTimeout(function(){var a=b.querySelector("button.ytp-ad-skip-button");a&&a.click()},2E3));a.overridespeeds?d.playbackRate=a.speed:b.setPlaybackRate(a.speed)}}catch(w){}}function n(a){a.setAttribute("style","display:block!important");clearTimeout(r);r=setTimeout(function(){a.setAttribute("style","display:none!important")},1500)}function f(){var b=document.querySelector(".html5-video-player")||document.querySelector("#player embed"),d=document.querySelector(".html5-main-video"),
h,f,l,p=m=!1;if(b){if("DIV"===b.nodeName&&!b.hasAttribute("efyt")){b.setAttribute("efyt","");var g=document.createElement("style");g.type="text/css";g.textContent="#enhancer-for-youtube-player-info{background-color:rgba(0,0,0,0.3);color:#fff;display:none;font-size:17px;left:0;padding:7px 0;position:absolute;text-align:center;top:0;width:100%;z-index:2147483647}";document.head.appendChild(g);var k=document.createElement("div");k.id="enhancer-for-youtube-player-info";b.appendChild(k);b.addEventListener("onAdStateChange",
function(c){1!==c||!a.pausevideos||document.hidden||l||a.removeads||(l=!0,document.dispatchEvent(new Event("efyt-pause-videos")),setTimeout(function(){l=!1},1E3));1===c&&a.removeads&&d?q(b,d):2!==c||a.removeads||(f=!0)});b.addEventListener("onStateChange",function(c){1!==c||!a.pausevideos||document.hidden||l||(l=!0,document.dispatchEvent(new Event("efyt-pause-videos")),setTimeout(function(){l=!1},1E3));if((1===c||3===c)&&a.selectquality&&!h)try{0<=b.getAvailableQualityLevels().indexOf(a.quality1)&&
(b.setPlaybackQuality(a.quality1),h=!0)}catch(e){b.setPlaybackQuality(a.quality1),h=!0}else if(-1===c||0===c)h=!1;1===c&&a.autopausevideos&&!f&&(document.hidden||!document.hidden&&a.pauseforegroundtab)?b.pauseVideo():2===c&&(f=!0)});b.parentNode.addEventListener("wheel",function(c){if(a.controlvolume||c.ctrlKey)try{if(c.ctrlKey){c.preventDefault();if(a.overridespeeds){var e=d.playbackRate;if(!a.reversemousewheeldirection&&0<c.deltaY||a.reversemousewheeldirection&&0>c.deltaY)e=parseFloat((e-a.speedvariation).toFixed(2)),
0>=e&&(e=a.speedvariation),d.playbackRate=e;else if(!a.reversemousewheeldirection&&0>c.deltaY||a.reversemousewheeldirection&&0<c.deltaY)e=parseFloat((e+a.speedvariation).toFixed(2)),d.playbackRate=e}else{var h=b.getAvailablePlaybackRates();e=b.getPlaybackRate();var g=h.indexOf(e);(!a.reversemousewheeldirection&&0<c.deltaY||a.reversemousewheeldirection&&0>c.deltaY)&&0<g?(e=h[g-1],b.setPlaybackRate(e)):(!a.reversemousewheeldirection&&0>c.deltaY||a.reversemousewheeldirection&&0<c.deltaY)&&g<h.length-
1&&(e=h[g+1],b.setPlaybackRate(e))}k.textContent="x"+e;n(k)}else if(a.controlvolumemousebutton&&p||!a.controlvolumemousebutton){c.preventDefault();var f=b.getVolume();!a.reversemousewheeldirection&&0<c.deltaY||a.reversemousewheeldirection&&0>c.deltaY?(f-=a.volumevariation,0>f&&(f=0)):(f+=a.volumevariation,100<f&&(f=100),b.isMuted()&&b.unMute());m=!0;b.setVolume(f);k.textContent=f;n(k)}}catch(y){}});b.parentNode.addEventListener("click",function(c){if(c.ctrlKey&&!c.shiftKey&&"function"===typeof b.getPlayerState&&
0<b.getPlayerState()){c.preventDefault();try{var e=a.speed;a.overridespeeds?d.playbackRate=e:b.setPlaybackRate(e);k.textContent="x"+e;n(k)}catch(x){}}});d&&(b.parentNode.addEventListener("mousedown",function(b){2===b.button&&a.controlvolumemousebutton&&(p=!0)}),d.addEventListener("contextmenu",function(b){if(a.controlvolumemousebutton&&m)return b.stopPropagation(),b.preventDefault(),p=m=!1}),b.parentNode.addEventListener("mouseleave",function(){p=m=!1}))}a.removeads&&d&&(g=document.createElement("style"),
g.type="text/css",g.textContent=".ytp-ad-progress-list, .ytp-ad-overlay-slot, .ytp-ad-overlay-ad-info-dialog-container, .ytp-ad-persistent-progress-bar-container{display:none !important}",document.head.appendChild(g),"function"===typeof b.getAdState&&1===b.getAdState()&&q(b,d));try{a.removeannotations&&(g=document.createElement("style"),g.type="text/css",g.textContent=".ytp-iv-player-content, .ytp-iv-video-content, .ytp-ce-element{display:none !important}",document.head.appendChild(g),"function"===
typeof b.unloadModule&&b.unloadModule("annotations_module")),a.defaultvolume&&b.setVolume(a.volume),d&&a.overridespeeds?(d.playbackRate=a.speed,d.defaultPlaybackRate=a.speed):b.setPlaybackRate(a.speed),a.selectquality&&b.setPlaybackQuality(a.quality1)}catch(c){}}}var r,m;if("complete"===document.readyState)f();else{var t=new MutationObserver(function(a){a.forEach(function(a){if(null!==a.addedNodes)for(var b=a.addedNodes.length-1;0<=b;b--)if("VIDEO"===a.addedNodes[b].nodeName&&a.addedNodes[b].hasAttribute("class")&&
a.addedNodes[b].classList.contains("html5-main-video")||"EMBED"===a.addedNodes[b].nodeName)t.disconnect(),f()})});t.observe(document.documentElement,{childList:!0,subtree:!0});if(a.selectquality){var u=Date.now();localStorage["yt-player-quality"]='{"data":"'+a.quality1+'","expiration":'+(u+2592E6)+',"creation":'+u+"}"}}document.addEventListener("efyt-pause-video",function(a){try{(document.querySelector(".html5-video-player")||document.querySelector("#player embed")).pauseVideo()}catch(d){}})}.toString()+
")("+JSON.stringify(v)+")";document.documentElement.appendChild(f);document.addEventListener("efyt-pause-videos",function(a){try{chrome.runtime.sendMessage({enhancerforyoutube:"pause-videos"})}catch(q){}});chrome.runtime.onMessage.addListener(function(a,f,n){"enhancerforyoutube:pause-video"===a.message&&document.hidden&&document.dispatchEvent(new Event("efyt-pause-video"))})});