/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(b){function f(){var a={};this.name?a[this.name]=this.value:a[this.id]=this.checked;chrome.storage.local.set(a)}function ea(){for(var a=[],b=0;b<k.length;b++)k[b].checked&&a.push(k[b].id);chrome.storage.local.set({toolbarbuttons:a.toString()})}function fa(){for(var a=[],b=0;b<m.length;b++)m[b].checked&&a.push(m[b].dataset.event);chrome.storage.local.set({autofocusevents:a.toString()})}function w(a){var b={};b[a?a:this.dataset.pref]=Date.now();chrome.storage.local.set(b)}function ha(a){a.preventDefault();
a=b.getElementById(this.dataset.target);if(a.classList.contains("hidden"))for(a=n.length-1;0<=a;a--)n[a].id===this.dataset.target?n[a].classList.remove("hidden"):n[a].classList.add("hidden");else a.classList.add("hidden")}function P(){b.querySelector("#custom-theme").parentNode.classList["custom"===b.querySelector('input[name="theme"]:checked').value?"remove":"add"]("hidden")}function Q(a){var f=b.querySelector(a);f.classList.remove("hidden");setTimeout(function(){f.classList.add("hidden")},1200)}
function G(){var a=b.querySelector("#channels"),f,c,e,k=chrome.i18n.getMessage("remove");a.textContent="";g.forEach(function(d){f=b.createElement("bdi");c=b.createElement("span");e=b.createElement("i");c.textContent=d;e.title=k;e.addEventListener("click",ia);c.appendChild(e);f.appendChild(c);a.appendChild(f)})}function ia(){g.splice(g.indexOf(this.parentNode.textContent),1);chrome.storage.local.set({whitelist:g.toString()});G()}function R(a){b.body.classList.add("overflow-hidden");l.style.display=
"block";a.style.display="block";a.scrollTop=0;l.classList.add("in");setTimeout(function(){b.body.classList.add("modal-open")},50)}function ja(a){b.body.classList.remove("modal-open");setTimeout(function(){a.style.display="none";l.classList.add("fade");l.classList.remove("in");setTimeout(function(){l.style.display="none";b.body.classList.remove("overflow-hidden")},300)},300)}var r=b.querySelectorAll(".i18n"),l=b.querySelector("#modal-backdrop"),k,n=b.querySelectorAll(".toolbar-btn-instructions"),m,
g,H=chrome.i18n.getMessage("locale_code"),t={autofocusevents:"ads,annotations,cinema,size,boost,loop,speed,filters",autopausevideos:!0,backgroundcolor:"#000000",backgroundopacity:85,blur:0,brightness:100,cinemamode:!1,cinemamodewideplayer:!0,contrast:100,controlvolume:!1,controlvolumemousebutton:!1,customtheme:"",date:0,defaultvolume:!1,disableautoplay:!1,disablepreloading:!1,enablefilters:!1,executescript:!1,expanddescription:!1,grayscale:0,huerotate:0,filter:"none",ignoreplaylists:!0,message:!1,
invert:0,newestcomments:!1,overridespeeds:!0,pauseforegroundtab:!1,pausevideos:!0,permissions:!1,pinnedplayer:!0,pinnedplayerposition:"_top-left",pinnedplayersize:"_400x225",quality1:"hd1080",quality2:"hd720",quality3:"large",quality4:"medium",removeads:!1,removeannotations:!1,reversemousewheeldirection:!1,saturate:100,script:"",selectquality:!1,sepia:0,slideeffect:!1,speed:1,speedvariation:.1,theatermode:!1,theme:"default",toolbarbuttons:"clean,cinema,resize,detach,boost,loop,speed,options",toolbarbackgroundcolor:"#ffffff",
toolbarbordercolor:"#cccccc",toolbarcolor:"#000000",toolbarcoloractive:"#000000",toolbaropacity:30,toolbartooltips:!0,transparency:!1,visitor_info1_live:"",volume:50,volumevariation:5,whitelist:"Google Chrome",wideplayer:!1,wideplayerviewport:!1};b.documentElement.lang=H.replace("_","-");b.body.classList.add(H);for(var e=r.length-1;0<=e;e--)r[e].textContent=chrome.i18n.getMessage(r[e].dataset.text);b.querySelector("#share").addEventListener("click",function(a){a.preventDefault();if(!this.dataset.clicked)for(this.dataset.clicked=
!0,a=b.querySelectorAll("#social a"),e=a.length-1;0<=e;e--)a[e].addEventListener("click",w),a[e].addEventListener("contextmenu",w),a[e].title=chrome.i18n.getMessage(a[e].dataset.title);b.querySelector("#social").classList.toggle("hidden")});chrome.storage.local.get(t,function(a){var e=["#toolbarbackgroundcolor","#toolbarbordercolor","#toolbarcolor","#toolbarcoloractive"];e.forEach(function(ka){var c=b.querySelector(ka);c.value=a[c.id];c.addEventListener("input",function(){a[c.id]=this.value;var b=
{};b[c.id]=this.value;chrome.storage.local.set(b)});c.addEventListener("change",f)});b.querySelector("#restore-default-colors").addEventListener("click",function(a){a.preventDefault();e.forEach(function(a){a=b.querySelector(a);a.value=t[a.id];a.dispatchEvent(new Event("change"))})});"#slideeffect #toolbartooltips #cinemamode #cinemamodewideplayer #reversemousewheeldirection #removeannotations #wideplayer #wideplayerviewport #enablefilters #pausevideos #disableautoplay #expanddescription #newestcomments #executescript".split(" ").forEach(function(c){c=
b.querySelector(c);c.checked=a[c.id];c.addEventListener("click",f)});var c=b.querySelector("#transparency"),l=b.querySelector("#toolbaropacity"),n=b.querySelector("#toolbaropacity-preview");c.checked=a.transparency;c.addEventListener("click",function(){l.disabled=!this.checked;chrome.storage.local.set({transparency:this.checked})});l.value=100-a.toolbaropacity;l.disabled=!a.transparency;l.addEventListener("input",function(){var b=parseInt(this.value,10);a.toolbaropacity=100-b;n.textContent=b+"%";
chrome.storage.local.set({toolbaropacity:a.toolbaropacity})});n.textContent=100-a.toolbaropacity+"%";k=b.querySelectorAll(".toolbar-btn");var d=a.toolbarbuttons.split(",");for(c=0;c<k.length;c++)k[c].checked=-1<d.indexOf(k[c].id)?!0:!1,k[c].addEventListener("click",ea);d=b.querySelectorAll(".toolbar-btns sup.info");for(c=0;c<d.length;c++)d[c].addEventListener("click",ha);c=b.querySelector("#backgroundcolor");d=b.querySelector("#backgroundopacity");var r=b.querySelector("#opacity"),w=b.querySelector("#cinemamode-background"),
I=function(){var b=a.backgroundcolor.replace("#",""),c=parseInt(b.substring(0,2),16),d=parseInt(b.substring(2,4),16);b=parseInt(b.substring(4,6),16);r.textContent=a.backgroundopacity+"%";w.style.backgroundColor="rgba("+c+","+d+","+b+","+a.backgroundopacity/100+")"};c.value=a.backgroundcolor;c.addEventListener("input",function(){a.backgroundcolor=this.value;I();chrome.storage.local.set({backgroundcolor:this.value})});c.addEventListener("change",f);d.value=a.backgroundopacity;d.addEventListener("input",
function(){a.backgroundopacity=parseInt(this.value,10);I();chrome.storage.local.set({backgroundopacity:a.backgroundopacity})});I();var u=b.querySelector("#playback-speed"),v=b.querySelector("#custom-playback-speed");c=b.querySelector("#overridespeeds");var x=b.querySelector("#speedvariation");d=b.querySelector("#defaultvolume");var y=b.querySelector("#volume"),S=b.querySelector("#volume-preview"),p=b.querySelector("#controlvolume"),z=b.querySelector("#controlvolumemousebutton"),A=b.querySelector("#volumevariation"),
T=b.querySelector("#pinnedplayer"),B=b.querySelector("#pinnedplayersize"),C=b.querySelector("#pinnedplayerposition");u.value=a.overridespeeds?1:a.speed;u.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});v.value=a.overridespeeds?a.speed:1;v.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});a.overridespeeds&&(u.classList.add("hidden"),v.classList.remove("hidden"));c.checked=a.overridespeeds;c.addEventListener("click",
function(){x.disabled=!this.checked;var a=b.querySelector("#playback-speed-label");a.classList.add("animated","blink");setTimeout(function(){a.classList.remove("animated","blink")},2400);u.classList.toggle("hidden");v.classList.toggle("hidden");chrome.storage.local.set({overridespeeds:this.checked,speed:parseFloat(this.checked?v.value:u.value)})});x.value=a.speedvariation;x.disabled=!a.overridespeeds;x.addEventListener("change",function(){chrome.storage.local.set({speedvariation:parseFloat(this.value)})});
d.checked=a.defaultvolume;d.addEventListener("click",function(){y.disabled=!this.checked;chrome.storage.local.set({defaultvolume:this.checked})});y.value=a.volume;y.disabled=!a.defaultvolume;y.addEventListener("input",function(){a.volume=parseInt(this.value,10);S.textContent=a.volume;chrome.storage.local.set({volume:a.volume})});S.textContent=a.volume;p.checked=a.controlvolume;p.addEventListener("click",function(){z.disabled=!this.checked;A.disabled=!this.checked;chrome.storage.local.set({controlvolume:this.checked})});
z.checked=a.controlvolumemousebutton;z.disabled=!a.controlvolume;z.addEventListener("click",f);A.value=a.volumevariation;A.disabled=!a.controlvolume;A.addEventListener("change",function(){chrome.storage.local.set({volumevariation:parseInt(this.value,10)})});T.checked=a.pinnedplayer;T.addEventListener("click",function(){B.disabled=!this.checked;C.disabled=!this.checked;chrome.storage.local.set({pinnedplayer:this.checked})});B.value=a.pinnedplayersize;B.disabled=!a.pinnedplayer;B.addEventListener("change",
f);C.value=a.pinnedplayerposition;C.disabled=!a.pinnedplayer;C.addEventListener("change",f);c=b.querySelector("#removeads");var U=b.querySelector("#whitelist"),V=b.querySelector("#channel");d=b.querySelector("#whitelist-channel-btn");(c.checked=a.removeads)&&U.classList.remove("hidden");c.addEventListener("click",function(){U.classList.toggle("hidden");chrome.storage.local.set({removeads:this.checked})});g=""!==a.whitelist?a.whitelist.split(","):[];0<g.length&&G();d.addEventListener("click",function(){var a=
V.value.replace(/,/g,"").trim();if(""!==a&&0>g.indexOf(a)){g.push(a);try{g.sort(function(a,b){return a.localeCompare(b)})}catch(la){g.sort()}chrome.storage.local.set({whitelist:g.toString()});G()}V.value=""});var J=b.querySelector("#permissions-granted"),q=b.querySelector("#grant-permissions");c=b.querySelector("#revoke-permissions");var W={permissions:["tabs","webNavigation","webRequest","webRequestBlocking"]};q.addEventListener("click",function(){chrome.permissions.request(W,function(a){chrome.runtime.lastError&&
(b.documentElement.dataset.e=1);a&&(J.classList.remove("hidden"),q.classList.add("hidden"),chrome.storage.local.set({permissions:!0},function(){chrome.runtime.sendMessage({enhancerforyoutube:"permissions-granted"},function(a){chrome.runtime.lastError&&(b.documentElement.dataset.e=1)})}))})});c.addEventListener("click",function(){J.classList.add("hidden");q.classList.remove("hidden");q.disabled=!0;chrome.storage.local.set({permissions:!1},function(){chrome.runtime.sendMessage({enhancerforyoutube:"permissions-revoked"},
function(a){chrome.runtime.lastError&&(b.documentElement.dataset.e=1);chrome.permissions.remove(W);setTimeout(function(){q.disabled=!1},3E3)})})});a.permissions&&(J.classList.remove("hidden"),q.classList.add("hidden"));c=b.querySelector("#autopausevideos");var D=b.querySelector("#pauseforegroundtab"),E=b.querySelector("#ignoreplaylists"),F=b.querySelector("#disablepreloading");c.checked=a.autopausevideos;c.addEventListener("click",function(){D.disabled=!this.checked;E.disabled=!this.checked;F.disabled=
!this.checked;chrome.storage.local.set({autopausevideos:this.checked})});D.checked=a.pauseforegroundtab;D.disabled=!a.autopausevideos;D.addEventListener("click",f);E.checked=a.ignoreplaylists;E.disabled=!a.autopausevideos;E.addEventListener("click",f);F.checked=a.disablepreloading;F.disabled=!a.autopausevideos;F.addEventListener("click",f);var K=b.querySelector("#selectquality"),X=["#quality1","#quality2","#quality3","#quality4"],L=0;K.checked=a.selectquality;K.addEventListener("click",function(){X.forEach(function(a){b.querySelector(a).disabled=
!K.checked});chrome.storage.local.set({selectquality:this.checked})});X.forEach(function(c){c=b.querySelector(c);var d=parseInt(window.getComputedStyle(c.parentNode.querySelector("label"),null).getPropertyValue("width"),10);c.value=a[c.id];c.disabled=!a.selectquality;c.addEventListener("change",f);d>L&&(L=d)});b.querySelectorAll("label.quality").forEach(function(a){a.style.minWidth=L/parseInt(window.getComputedStyle(b.body,null).getPropertyValue("font-size"),10)+"em"});m=b.querySelectorAll(".focus");
for(c=0;c<m.length;c++)m[c].checked=0<=a.autofocusevents.indexOf(m[c].dataset.event)?!0:!1,m[c].addEventListener("click",fa);c=b.querySelector("#theatermode");c.checked=a.theatermode;c.addEventListener("click",function(){chrome.cookies.set({url:"https://www.youtube.com/watch",name:"wide",value:this.checked?"1":"0",domain:".youtube.com",path:"/",expirationDate:Math.floor(Date.now()/1E3)+31556926});chrome.storage.local.set({theatermode:this.checked})});d=b.querySelectorAll('input[name="theme"]');c=
d.length-1;var M=b.querySelector("#custom-theme");for(p=b.querySelector("#custom-theme-btn");0<=c;c--)d[c].value===a.theme&&(d[c].checked=!0),d[c].addEventListener("click",P),d[c].addEventListener("click",f);P();M.value=a.customtheme;M.setAttribute("placeholder",chrome.i18n.getMessage("custom_theme_instructions"));p.addEventListener("click",function(){Q("#custom-theme-spinner");chrome.storage.local.set({customtheme:M.value})});var N=b.querySelector("#custom-script");c=b.querySelector("#custom-script-btn");
N.value=a.script;N.setAttribute("placeholder",chrome.i18n.getMessage("custom_script_instructions"));c.addEventListener("click",function(){Q("#custom-script-spinner");chrome.storage.local.set({script:N.value})});c=b.querySelector("#export-modal-btn");d=b.querySelector("#import-modal-btn");var h=b.querySelector("#backup-modal"),Y=h.querySelector(".close-modal"),Z=h.querySelector("#export-modal-content"),aa=h.querySelector("#export-textarea"),ba=h.querySelector("#import-modal-content"),O=h.querySelector("#import-error"),
ca=h.querySelector("#import-textarea");p=h.querySelector("#import-btn");var da=h.querySelector("#backup-modal-footer");c.addEventListener("click",function(){Z.classList.remove("hidden");R(h);chrome.storage.local.get(null,function(a){var b={};b.version=chrome.runtime.getManifest().version;b.settings={};Object.keys(t).forEach(function(c){b.settings[c]="undefined"===typeof a[c]?t[c]:a[c]});aa.value=JSON.stringify(b)})});d.addEventListener("click",function(){ba.classList.remove("hidden");da.classList.remove("hidden");
R(h)});Y.addEventListener("click",function(){ja(h);setTimeout(function(){Z.classList.add("hidden");ba.classList.add("hidden");O.classList.add("hidden");ca.value="";da.classList.add("hidden")},600)});aa.addEventListener("click",function(){this.select()});p.addEventListener("click",function(){var a=ca.value.trim(),c={};if(""!==a){try{a=JSON.parse(a)}catch(ma){O.classList.remove("hidden");return}"object"===typeof a.settings?(Object.keys(a.settings).forEach(function(b){typeof t[b]===typeof a.settings[b]&&
(c[b]=a.settings[b])}),chrome.storage.local.clear(function(){chrome.runtime.lastError&&(b.documentElement.dataset.e=1);chrome.storage.local.set(c,function(){window.scrollTo(0,0);b.location.reload()})})):O.classList.remove("hidden")}});b.addEventListener("keydown",function(a){27===a.keyCode&&Y.click()});b.querySelector("#version").textContent="Version: "+chrome.runtime.getManifest().version+" "+H+" ["+chrome.i18n.getUILanguage()+"]";b.querySelector("#device").textContent="Device: "+navigator.userAgent+
" "+a.visitor_info1_live+" "+window.screen.width+"x"+window.screen.height+" ["+window.screen.availWidth+"x"+window.screen.availHeight+"]"})})(document);