/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(a){if(!window.EnhancerForYouTube){var Oa=function(a){var h;"undefined"===typeof a&&(h=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:h?h.customtheme:a,theme:c.theme}))},Aa=function(){if(k){for(var a=k.querySelectorAll("li"),d=c.toolbarbuttons.split(","),b=a.length-1;0<=b;b--)a[b].classList[-1<d.indexOf(a[b].dataset.name)?"remove":"add"]("hidden");k.querySelector('li[data-name="message"]').classList[c.message?
"remove":"add"]("hidden");""!==c.toolbarbuttons||c.message?(y.classList.remove("hidden"),Pa()):y.classList.add("hidden")}},ib=function(){oa();if(0===z[0].children.length){var a=q;z.slider({animate:"slow",range:!0,min:0,max:M,values:[q,A],start:function(c,b){a=q},slide:function(a,b){q=b.values[0];A=b.values[1];oa()},stop:function(c,b){q===M?(q=M-1,Ba(),oa()):A===q&&(A=q+1,Ba(),oa());a!==q&&d.seekTo(q)}})}else Ba();z.show();y.classList.add("extended")},Ba=function(){z.slider("values",[q,A])},oa=function(){Qa[0].textContent=
Ca(q)+" / "+Ca(A)},Ra=function(a){if(a.classList.contains("active"))clearInterval(ha),a.classList.remove("active"),z.hide(),y.classList.remove("extended"),g&&(g.loop=!1);else{a.classList.add("active");0===$("#enhancer-for-youtube-slider",k).length&&(z=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(k),Qa=$("<div />").addClass("start-end").appendTo(k));M=q=A=!1;var c=0,b=Y();ha=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?M?!b&&d.getCurrentTime()>=A?d.seekTo(q):
b||0!==d.getPlayerState()?(b&&!g&&M===A&&2>M-d.getCurrentTime()||b&&M!==A&&d.getCurrentTime()>=A)&&d.seekTo(q):d.playVideo():(M=A=parseInt(d.getDuration(),10),q=0,"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&(q=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,A=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):A),g&&(g.loop=!0),c=0,ib()):(c++,U())}catch(f){15<c&&clearInterval(ha),d=!1,g&&(g.loop=!1)}},1E3)}},Ca=function(a){a=Number(a);var c=
Math.floor(a/3600),b=Math.floor(a%3600/60);a=Math.floor(a%3600%60);return(0<c?c+":":"")+(0<b?(0<c&&10>b?"0":"")+b+":":"0:")+(10>a?"0":"")+a},Fa=function(){a.body.classList.remove("enhancer-for-youtube-pinned-player");Da||Ea();a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_"));window.scrollTo(0,0);a.body.classList.add("enhancer-for-youtube-cinema-mode");c.cinemamodewideplayer&&!a.body.classList.contains("enhancer-for-youtube-wide-player")&&
H("large");0<=c.autofocusevents.indexOf("cinema")&&u();k&&k.querySelector("i.cinema").parentNode.classList.add("active")},pa=function(){a.body.classList.remove("enhancer-for-youtube-cinema-mode");!c.wideplayer&&c.cinemamodewideplayer?H("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),a.body.classList.add("viewport"),d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY));0<=c.autofocusevents.indexOf("cinema")&&u();k&&k.querySelector("i.cinema").parentNode.classList.remove("active")},
ia=function(a){P=!0;if(c.controlvolumemousebutton&&qa)return a.stopPropagation(),a.preventDefault(),ra=qa=!1},Sa=function(a){P=!0;2===a.button&&c.controlvolumemousebutton&&(ra=!0)},Z=function(){var a=[c.quality1,c.quality2,c.quality3,c.quality4],e=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||("video"===D?U():Ga()),-1!==d.getPlayerState()){for(var c=0,h=!1,g,v=d.getAvailableQualityLevels();c<a.length&&!h;c++)for(var k in v)if(a[c]===v[k]){h=a[c];break}g=h?h:"auto";g!==d.getPlaybackQuality()?
I||(I=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(g),d.playVideo()):d.setPlaybackQuality(g)):g===d.getPlaybackQuality()&&(I=!0,clearInterval(e),clearTimeout(b))}}catch(sa){d=!1}},500),b=setTimeout(function(){clearInterval(e)},3E4)},la=function(h){d||U();if(d&&d.hasAttribute("flashvars")){clearInterval(ha);clearInterval(aa);k&&z&&0<z[0].children.length&&(k.querySelector("i.loop").parentNode.classList.remove("active"),z.slider("destroy"),z[0].style.display="none");var e="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
b=function(b){for(var a=e.length-1;0<=a;a--)if(b===e[a])return!0;return!1},f=d.getAttribute("flashvars"),p=d.cloneNode(!0);f=f.split("&");for(var l=[],v,ja,sa=0;sa<f.length;sa++)v=f[sa].split("="),ja=v[0],v=v[1],b(ja)||l.push(ja+"="+v);b=l.join("&");0>b.indexOf("enablejsapi")&&(b+="&enablejsapi=1");0>b.indexOf("iv_load_policy")&&(b+="&iv_load_policy=1");0>b.indexOf("autoplay")&&(b+="&autoplay=1");c.removeannotations&&(b=b.replace("iv_load_policy=1","iv_load_policy=3"));p.setAttribute("flashvars",
b);m.textContent="";m.appendChild(p);Ha(m);I=!1;c.autopausevideos&&!c.disablepreloading?ta():c.selectquality&&Z()}else if(d){if(h||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(ba)return;try{Number.isFinite(g.duration)?7<d.getDuration()-g.duration&&(ba=!0,(p=d.querySelector("button.ytp-ad-skip-button"))?p.click():(g.currentTime=g.duration-.5,setTimeout(function(){var b=d.querySelector("button.ytp-ad-skip-button");b&&b.click()},2E3)),ka=0,c.overridespeeds?
g.playbackRate=n:d.setPlaybackRate(n)):setTimeout(function(){la(h)},50)}catch(Ta){if(!g||(0<Ta.message.indexOf("currentTime")||"IndexSizeError"===Ta.message)&&g!=a.querySelector("video.html5-main-video"))return}}else Ia();0<=c.autofocusevents.indexOf("ads")&&u()}else setTimeout(function(){la(h)},100)},Ia=function(){d.classList.add("ads-removed")},ma=function(){try{"object"===typeof ca&&(ca.disconnect(),ca=void 0);var a=d.querySelector("button.ytp-settings-button"),e=d.querySelector("div.ytp-settings-menu");
if(!I&&a&&e){ca=new MutationObserver(function(b){b.forEach(function(b){if(null!==b.addedNodes)for(var a=b.addedNodes.length-1;0<=a;a--)if("DIV"===b.addedNodes[a].nodeName&&b.addedNodes[a].classList.contains("ytp-menuitem")&&/\d{3,4}[p,s]/.test(b.addedNodes[a].textContent))b.addedNodes[a].click();else if("DIV"===b.addedNodes[a].nodeName&&b.addedNodes[a].classList.contains("ytp-quality-menu")){a=0;var d=!1,h={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres",
"4320s 8K":"highres","2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160","2160p 4K":"hd2160","2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60 HD":"hd720","720p50 HD":"hd720","720p48 HD":"hd720",
"720p HD":"hd720","720s HD":"hd720","480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},f=b.addedNodes[a].querySelectorAll("div.ytp-menuitem");0<f.length&&[c.quality1,c.quality2,c.quality3,c.quality4].forEach(function(b){if(!d){for(;a<f.length;a++)if(b===h[f[a].textContent]){f[a].click();d=!0;break}a=0}});d||f[0].click();I=!0;e.classList.remove("hidden");ca.disconnect();u()}})});ca.observe(e,{childList:!0,subtree:!0});for(var b=
e.querySelectorAll("div.ytp-menuitem"),f,g=b.length-1;0<=g;g--)if(/\d{3,4}[p,s]/.test(b[g].textContent)){f=b[g];break}e.classList.add("hidden");setTimeout(function(){e.classList.remove("hidden")},2500);f?(a.click(),f.click()):a.click()}else if(!I){var l=d.getAvailableQualityLevels();0<=l.indexOf(c.quality1)?d.setPlaybackQuality(c.quality1):0<=l.indexOf(c.quality2)?d.setPlaybackQuality(c.quality2):0<=l.indexOf(c.quality3)?d.setPlaybackQuality(c.quality3):0<=l.indexOf(c.quality4)&&d.setPlaybackQuality(c.quality4)}}catch(v){}},
H=function(d){try{var h=a.body.classList.contains("enhancer-for-youtube-wide-player");x&&!J&&(J=x.classList.contains("watch-stage-mode")&&!a.body.classList.contains("enhancer-for-youtube-wide-player"));if("large"===d||!d&&!h){Da||Ea();var b=a.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]')||a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');if(b)var f=b.parentNode.parentNode;if(J&&f){f.click();
var g=setInterval(function(){!x.classList.contains("watch-non-stage-mode")||x.classList.contains("watch-wide")||x.classList.contains("watch-stage-mode")||(clearInterval(g),J=!0,Ua(f,"1"))},20)}else Ua(f,J?"1":"0")}else if("default"===d||!d&&h){var l=a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');if(l)var k=l.parentNode.parentNode;k?k.click():k||J||(x.classList.add("watch-non-stage-mode"),x.classList.remove("watch-wide"),x.classList.remove("watch-stage-mode"));
J||k||setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"})}))},250);a.body.classList.remove("enhancer-for-youtube-wide-player","viewport","_viewport_");k&&J&&(g=setInterval(function(){!x.classList.contains("watch-non-stage-mode")||x.classList.contains("watch-wide")||x.classList.contains("watch-stage-mode")||(clearInterval(g),J=!1,k.click())},20))}}catch(ja){}0<=c.autofocusevents.indexOf("size")&&
u();window.dispatchEvent(new Event("resize"))},Ua=function(h,e){h?h.click():(x.classList.add("watch-wide"),x.classList.add("watch-stage-mode"),x.classList.remove("watch-non-stage-mode"));a.body.classList.add("enhancer-for-youtube-wide-player");c.wideplayerviewport&&ua&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},
80)));setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:e})}))},250)},Va=function(c){P=!0;a.removeEventListener("keydown",Va,!0)},ta=function(){if(c.ignoreplaylists&&Y()||!c.pauseforegroundtab&&!V&&!a.hidden)Q=!0,d.hasAttribute("efyt-muted")&&na(),c.selectquality&&(r?Z():ma()),!c.pausevideos||a.hidden||N||(N=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),
setTimeout(function(){N=!1},1E3));else{clearInterval(aa);try{if(c.disablepreloading&&"video"===D&&V)d.stopVideo(),Q=!0,d.hasAttribute("efyt-muted")&&na(),d.addEventListener("onStateChange",function l(b){if(1===b){d.removeEventListener("onStateChange",l);c.selectquality&&r&&Z();try{var h=a.location.href.match(/&t=(\d+)s?/);h&&d.seekTo(parseInt(h[1],10));d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded",c.removeannotations?0:1)}catch(ja){}}});
else{d.pauseVideo();Q=!0;var h=a.location.href.match(/&t=(\d+)s?/);h?d.seekTo(parseInt(h[1],10)):V&&!P&&d.seekTo(0);d.hasAttribute("efyt-muted")&&na()}}catch(f){var e,b=0;aa=setInterval(function(){try{d&&"function"===typeof d.getPlayerState||(b++,"video"===D?U():Ga()),e=d.getPlayerState(),a.hidden?-1!==e&&c.disablepreloading?d.stopVideo():2===e||c.disablepreloading||d.pauseVideo():-1!==e&&5!==e&&c.pauseforegroundtab&&c.disablepreloading?d.stopVideo():2!==e&&c.pauseforegroundtab&&!c.disablepreloading?
(-1!==e&&5!==e||d.playVideo(),3!==e&&d.pauseVideo()):clearInterval(aa)}catch(p){200<b&&clearInterval(aa),d=!1}},50)}u()}},Wa=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();n=c.speed;try{c.overridespeeds?g.playbackRate=n:d.setPlaybackRate(n),"I"===a.target.nodeName&&c.toolbartooltips?w.textContent=B.speed+" x"+n:(R.textContent="x"+n,Ja())}catch(e){}0<=c.autofocusevents.indexOf("speed")&&u()}},Ja=function(){R.setAttribute("style",
"display:block!important");clearTimeout(Xa);Xa=setTimeout(function(){R.setAttribute("style","display:none!important")},1500)},Pa=function(){y.style.marginLeft="-"+k.getBoundingClientRect().width/2+"px"},K=function(a,d){a.addEventListener("mouseenter",function(b){c.toolbartooltips&&(w.textContent=d,w.style.left=b.target.getBoundingClientRect().left+b.target.clientWidth/2-w.clientWidth/2+"px",w.classList.add("visible"))});a.addEventListener("mouseleave",function(){w.classList.remove("visible")})},Ya=
function(){try{E.max=g.duration,E.value=g.currentTime}catch(h){}},va=function(a){a.preventDefault();if(!r){try{if(c.overridespeeds){var e=g.playbackRate;if(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)e=parseFloat((e-c.speedvariation).toFixed(2)),0>=e&&(e=c.speedvariation),g.playbackRate=e;else if(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)e=parseFloat((e+c.speedvariation).toFixed(2)),g.playbackRate=e}else{var b=d.getAvailablePlaybackRates();
e=d.getPlaybackRate();var h=b.indexOf(e);(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)&&0<h?(e=b[h-1],d.setPlaybackRate(e)):(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)&&h<b.length-1&&(e=b[h+1],d.setPlaybackRate(e))}n=e;"I"===a.target.nodeName&&c.toolbartooltips?w.textContent=B.speed+" x"+e:(R.textContent="x"+e,Ja())}catch(p){}0<=c.autofocusevents.indexOf("speed")&&u()}},kb=function(a){if(a.ctrlKey)va(a);else if(c.controlvolume&&
(c.controlvolumemousebutton&&ra||!c.controlvolumemousebutton)){a.preventDefault();try{var e=d.getVolume();!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY?(e-=c.volumevariation,0>e&&(e=0)):(e+=c.volumevariation,100<e&&(e=100),d.isMuted()&&d.unMute());qa=!0;d.setVolume(e);R.textContent=e;Ja();c.defaultvolume&&(c.volume=e);var b=Date.now();a=0<e?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","expiration":'+(b+2592E6)+
',"creation":'+b+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","creation":'+b+"}"}catch(f){}}},lb=function(a){a.shiftKey?Za(a):a.ctrlKey&&Wa(a)},Za=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var d=""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?!1:!0;g.style["-webkit-filter"]=d?"":c.filter;g.style.filter=d?"":c.filter;k.querySelector("i.filters").parentNode.classList[d?"remove":"add"]("active")}catch(b){}0<=
c.autofocusevents.indexOf("filters")&&u()}},Ha=function(c){c.querySelector("#enhancer-for-youtube-player-info")||(a.querySelector("#enhancer-for-youtube-player-info")||(R=a.createElement("div"),R.id="enhancer-for-youtube-player-info"),c.appendChild(R))},$a=function(c){var e=a.location.href.match(/&?v=([^&\?]+)/)[1]+"?autoplay=1",b=a.location.href.match(/&?list=([^&\?]+)/);b&&(e+="&list="+b[1]);try{d.pauseVideo();var f=d.getCurrentTime();f&&(e+="&start="+parseInt(f,10));c&&d.stopVideo()}catch(p){}a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"detach",params:e})}))},Ka=function(a){if(c.toolbartooltips){var d="";try{d=" x"+g.playbackRate}catch(b){}w.textContent=B.speed+d;w.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/2-w.clientWidth/2+"px";w.classList.add("visible")}},mb=function(){if(!y){C=a.createElement("div");y=a.createElement("div");k=a.createElement("div");w=a.createElement("div");var h=a.createDocumentFragment(),e=a.createElement("ul"),b=a.createElement("li"),f=
a.createElement("i");C.id="enhancer-for-youtube-background";C.style.visibility="hidden";C.addEventListener("click",function(){pa()});h.appendChild(C);y.id="enhancer-for-youtube-toolbar-wrapper";k.id="enhancer-for-youtube-toolbar";w.id="enhancer-for-youtube-tooltip";h.appendChild(w);k.style.visibility="hidden";c.transparency&&k.classList.add("transparency");c.slideeffect&&k.classList.add("slide-effect");b.dataset.name=f.className="message";b.appendChild(f);f=a.createElement("i");f.className="badge";
b.appendChild(f);b.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-message"})}))});K(b,B.message);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="clean";b.appendChild(f);b.addEventListener("click",function(){wa=!0;ba=!1;la()});b.addEventListener("contextmenu",function(a){a.preventDefault();d||U();try{var b=d.getAttribute("annotations-module-loaded");d["1"===b?"unloadModule":
"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===b?0:1);0<=c.autofocusevents.indexOf("annotations")&&u()}catch(jb){}return!1});K(b,B.remove_ads);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="cinema";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?pa():Fa()});K(b,B.cinema_mode);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=
f.className="resize";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),H())});b.addEventListener("contextmenu",function(b){b.preventDefault();b=a.querySelector("#masthead-positioner");try{window.scrollTo(window.scrollX,
m.getBoundingClientRect().top-(a.body.classList.contains("viewport")?0:b?b.clientHeight:50)+window.scrollY)}catch(vb){}return!1});K(b,B.resize_player);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="detach";b.appendChild(f);b.addEventListener("click",function(){$a(!1)});b.addEventListener("contextmenu",function(a){a.preventDefault();$a(!0);return!1});K(b,B.detach_player);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"boost";b.appendChild(f);b.addEventListener("click",function(){if(g){if(!da){var a=new (window.AudioContext||window.webkitAudioContext),b=a.createMediaElementSource(g);da=a.createGain();b.connect(da);da.connect(a.destination)}this.classList.contains("active")?(da.gain.value=1,this.classList.remove("active")):(da.gain.value=3,this.classList.add("active"));0<=c.autofocusevents.indexOf("boost")&&u()}});K(b,B.boost_volume);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=
f.className="loop";b.appendChild(f);b.addEventListener("click",function(){if(ab)Ra(this);else{ab=!0;t=a.createElement("link");t.rel="stylesheet";t.href=G+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(t);var b=this,d=a.createElement("script");d.src=G+"/vendor/jquery/jquery-3.3.1.min.js";d.onload=function(){d=a.createElement("script");d.src=G+"/vendor/jquery/jquery-ui.min.js";d.onload=function(){Ra(b)};a.head.appendChild(d)};a.head.appendChild(d)}0<=c.autofocusevents.indexOf("loop")&&u()});
K(b,B.loop_video);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="slowdown";b.appendChild(f);f=a.createElement("i");f.className="minus";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",function(){va({target:{nodeName:"I"},deltaY:1,preventDefault:function(){}})});b.addEventListener("mouseenter",Ka);b.addEventListener("mouseleave",function(){w.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");
b.dataset.name=f.className="speed";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",Wa);b.addEventListener("wheel",va);b.addEventListener("mouseenter",Ka);b.addEventListener("mouseleave",function(){w.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="speedup";b.appendChild(f);f=a.createElement("i");f.className="plus";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",function(){va({target:{nodeName:"I"},
deltaY:-1,preventDefault:function(){}})});b.addEventListener("mouseenter",Ka);b.addEventListener("mouseleave",function(){w.classList.remove("visible")});e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="filters";b.appendChild(f);r&&b.classList.add("not-allowed");b.addEventListener("click",Za);b.addEventListener("touchstart",function(b){if(this.hasAttribute("ui"))a.querySelector("#enhancer-for-youtube-filters").classList[this.classList.contains("active")?"add":
"remove"]("hidden");else a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})}))});b.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})})));return!1});K(b,B.filters);e.appendChild(b);b=a.createElement("li");
f=a.createElement("i");b.dataset.name=f.className="script";b.appendChild(f);b.addEventListener("click",function(){u();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}))});K(b,B.custom_script);e.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="options";b.appendChild(f);b.addEventListener("click",function(){u();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-options"})}))});
K(b,B.options);e.appendChild(b);k.appendChild(e);y.appendChild(k);h.appendChild(y);E=a.createElement("progress");E.id="enhancer-for-youtube-progress";E.max=1;E.value=0;E.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth));u()});E.addEventListener("mouseenter",function(){S.classList.add("visible")});E.addEventListener("mouseleave",function(){S.classList.remove("visible")});E.addEventListener("mousemove",function(a){g&&(S.textContent=
Ca(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),S.style.left=a.pageX-S.getBoundingClientRect().width/2+"px")});h.appendChild(E);S=a.createElement("div");S.id="enhancer-for-youtube-progress-tooltip";h.appendChild(S);e=a.createElement("div");e.id="enhancer-for-youtube-unpin-player";e.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});h.appendChild(e);a.body.appendChild(h);setTimeout(function(){Aa();Pa();C.style.visibility="";k.style.visibility=
""},500);if((h=d.querySelector(".ytp-right-controls"))&&!h.querySelector(".efy-ytp-keyboard-shortcuts")){var p,l=a.createElement("div");e=a.createElement("div");b=a.createElement("span");var v=a.createElement("button");f=a.createElementNS("http://www.w3.org/2000/svg","svg");var n=a.createElementNS("http://www.w3.org/2000/svg","path"),q=h.querySelector('button:not([style*="display"])');b.className="ytp-tooltip-text";b.textContent=B.keyboard_shortcuts+" \ud83d\uddd7";e.appendChild(b);e.className="ytp-tooltip-text-wrapper";
l.appendChild(e);l.className="ytp-bottom";l.style.display="none";d.appendChild(l);v.className="ytp-button efy-ytp-keyboard-shortcuts";v.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"keyboard-shortcuts"})}))});v.addEventListener("mouseenter",function(a){q.dispatchEvent(new Event("mouseover"));q.dispatchEvent(new Event("mouseout"));p||(p=d.querySelector(".ytp-tooltip"));p&&""!==p.style.top&&(l.classList.add("ytp-tooltip"),
l.style.display="block",l.style.top=p.style.top,l.style.left=v.offsetLeft+a.target.getBoundingClientRect().width-l.getBoundingClientRect().width/2+"px")});v.addEventListener("mouseleave",function(){l.style.display="none";l.classList.remove("ytp-tooltip")});f.setAttributeNS(null,"version","1.1");f.setAttributeNS(null,"viewBox","0 0 36 36");f.setAttributeNS(null,"height","100%");f.setAttributeNS(null,"width","100%");n.setAttributeNS(null,"d","m26 11h-16c-1.1 0-1.99.9-1.99 2l-.01 10c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2v-10c0-1.1-.9-2-2-2zm-9 3h2v2h-2zm0 3h2v2h-2zm-3-3h2v2h-2zm0 3h2v2h-2zm-1 2h-2v-2h2zm0-3h-2v-2h2zm9 7h-8v-2h8zm0-4h-2v-2h2zm0-3h-2v-2h2zm3 3h-2v-2h2zm0-3h-2v-2h2z");
n.setAttributeNS(null,"fill","#fff");v.appendChild(f);f.appendChild(n);h.insertBefore(v,h.firstChild)}(new MutationObserver(function(b){b.forEach(function(b){try{!b.target.classList.contains("watch-non-stage-mode")||b.target.classList.contains("watch-wide")||b.target.classList.contains("watch-stage-mode")||(a.body.classList.remove("enhancer-for-youtube-wide-player"),J=!1,setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,
name:"wide",value:c.theatermode?"1":"0"})}))},250))}catch(jb){}})})).observe(x,{attributes:!0,attributeFilter:["class"]})}},Ea=function(){var c=a.documentElement.clientWidth,d=a.documentElement.clientHeight;if(c!==bb||d!==cb){bb=c;cb=d;var b=a.querySelector("#masthead-positioner");b=b?b.getBoundingClientRect().height:50;var f=k?k.getBoundingClientRect().height:29;var g=656>=c?240:1720<=c&&980<=d?720:1294<=c&&630<=d?480:360;if(parseInt(16/9*(d-b-f),10)>c){b=c-4;f=parseInt(b/(16/9),10);var l=f-g;var m=
240===g?0:g;var n=l;c=b;d=f;ua=!1}else f=parseInt(d-b-f,10),b=parseInt(16/9*f,10),l=f-g+(480===g?120:0),m=240===g?0:360,n=d-m,window.screen.height===d?(c-=4,d=parseInt(c/(16/9),10)):c=parseInt(16/9*d,10),ua=!0;var q=240===g?0:g;g=parseInt(b/2,10);var r=parseInt(c/2,10);var t=a.createElement("style");t.type="text/css";t.textContent="body.enhancer-for-youtube-wide-player .watch-stage-mode .player-height,body.enhancer-for-youtube-wide-player .watch-stage-mode embed#movie_player,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
f+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-height,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
d+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode .player-width,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+b+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-width,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
c+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-chrome-bottom{width:"+(b-24)+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-chrome-bottom{width:"+(c-24)+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode .player-width{left:-"+g+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-width{left:-"+
r+"px !important}body.enhancer-for-youtube-wide-player:not(.enhancer-for-youtube-cinema-mode) #player-playlist .watch-playlist{top:"+l+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) #player-playlist .watch-playlist{top:"+n+"px !important}body.enhancer-for-youtube-cinema-mode:not(.enhancer-for-youtube-wide-player) #player-playlist .watch-playlist{top:-"+q+"px !important}body.enhancer-for-youtube-cinema-mode:not(.enhancer-for-youtube-wide-player) .watch-stage-mode #player-playlist .watch-playlist{top:-360px !important}body.enhancer-for-youtube-wide-player.enhancer-for-youtube-cinema-mode #player-playlist .watch-playlist{top:-"+
m+"px !important}";a.head.appendChild(t);Da=!0}},db=function(){window.IntersectionObserver&&!m.hasAttribute("io")&&(m.setAttribute("io",1),La=new IntersectionObserver(function(h){if((0===h[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&0<window.scrollY||0<h[0].intersectionRatio&&.12>h[0].intersectionRatio)&&window.scrollY>m.offsetHeight-100&&W()){if(!d||!d.classList.contains("ended-mode")){g&&g.addEventListener("timeupdate",Ya);a.body.classList.add("enhancer-for-youtube-pinned-player");
try{g.style.top=""}catch(e){}0<=c.autofocusevents.indexOf("pin")&&u()}}else 0!==h[0].intersectionRatio&&(g&&g.removeEventListener("timeupdate",Ya),a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.dispatchEvent(new Event("resize")),r||nb())},{threshold:.12}),La.observe(m))},nb=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var c=m.clientHeight,e=g.clientHeight;d.clientHeight!==c?(d.style.width=m.clientWidth,d.style.height=
c,d.style.width="",d.style.height=""):e!==c&&(g.style.width=m.clientWidth,g.style.height=c,g.style.top="")}}catch(b){}},50)},ob=function(){Ma=setInterval(function(){try{if("function"!==typeof d.getPlayerState&&U(),0===d.getPlayerState()&&(clearInterval(Ma),!k.querySelector("i.loop").parentNode.classList.contains("active"))){var c=a.querySelector(".playlist-videos-container .playlist-videos-list li.currently-playing");if(c){var e=c.nextElementSibling;e&&(a.location.href=e.querySelector("a.playlist-video").href)}}}catch(b){}},
5E3)},na=function(){d.unMute();d.setVolume(c.defaultvolume?c.volume:parseInt(d.getAttribute("efyt-muted"),10));d.removeAttribute("efyt-muted")},u=function(){try{a.activeElement.blur(),d.focus({preventScroll:!0})}catch(h){}},Ga=function(){d=a.querySelector("#c4-player")},U=function(){d=a.querySelector("#movie_player")},Y=function(){return 0<a.location.href.indexOf("list=")},W=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/.*\/live/.test(a.location.href)},
xa=function(a,c){var b=parseInt(a.slice(1),16),d=0>c?0:255,e=0>c?-1*c:c,g=b>>16,h=b>>8&255;b&=255;return"#"+(16777216+65536*(Math.round((d-g)*e)+g)+256*(Math.round((d-h)*e)+h)+(Math.round((d-b)*e)+b)).toString(16).slice(1)},eb=function(){var d=a.createElement("style"),e=c.toolbarbackgroundcolor.replace("#",""),b=parseInt(e.substring(0,2),16),f=parseInt(e.substring(2,4),16);e=parseInt(e.substring(4,6),16);d.type="text/css";d.textContent="#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+
c.toolbarbackgroundcolor+";border-top:1px solid "+c.toolbarbordercolor+";border-right:1px solid "+c.toolbarbordercolor+";border-left:1px solid "+c.toolbarbordercolor+";color:"+c.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-toolbar li.active i{color:"+c.toolbarcoloractive+" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+c.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+
c.toolbarbackgroundcolor+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+xa(c.toolbarbackgroundcolor,-.1)+"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+xa(c.toolbarbackgroundcolor,-.1)+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+xa(c.toolbarbackgroundcolor,
-.15)+";border:1px solid "+xa(c.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+b+","+f+","+e+",0.85)}#enhancer-for-youtube-filters{background-color:"+c.toolbarbackgroundcolor+" !important;border:1px solid "+c.toolbarbordercolor+" !important;color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+c.toolbarcolor+" !important}";a.head.appendChild(d)},pb=function(){P=!0;fb=setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||
a.activeElement.classList.contains("ytp-volume-panel"))&&u()}catch(h){}},3E3)},qb=function(){P=!0;clearInterval(fb);ra=qa=!1},rb=function(a){try{100<=a&&setTimeout(function(){d.nextVideo()},2E3)}catch(e){}},gb=function(a){1===a&&(d.removeEventListener("onStateChange",gb),g&&c.overridespeeds?g.playbackRate=n:d.setPlaybackRate(n))},sb=function(a){"number"===typeof a&&(n=a)},tb=function(g){try{c.pausevideos&&!a.hidden&&1===g&&!N&&(c.autopausevideos&&Q||!c.autopausevideos)&&(N=!0,a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){N=!1},1E3)),!c.autopausevideos||Q||P||1!==g||ta(),c.selectquality&&!I&&1===g&&ma(),1===g?ba=!1:2===g&&(Q=!0),0===g&&"video"===D&&setTimeout(function(){d.classList.contains("ended-mode")&&(E.value=E.max)},500)}catch(e){}},ub=function(h){try{!c.pausevideos||a.hidden||1!==h||N||c.removeads||(N=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){N=
!1},1E3));c.removeads&&1===h||wa&&1===h?ka++:!c.removeads&&1===h&&d.hasAttribute("efyt-muted")&&na();if(c.removeads&&1===h&&3>ka&&0>ya.indexOf(F)||wa&&1===h&&3>ka)"video"===D?la(h):(g.currentTime=g.duration-.5,Ia());if(0===h||0===d.getAdState())ba=!1,d.addEventListener("onStateChange",gb)}catch(e){}},ea=function(){t||(t=a.createElement("link"),t.rel="stylesheet",t.href=G+"/youtube.css",a.head.appendChild(t),t=a.createElement("style"),t.type="text/css",t.textContent="#enhancer-for-youtube-background{background-color:"+
c.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+c.backgroundopacity/100+";visibility:visible}",a.head.appendChild(t),eb());D=d=m=O=g=wa=ba=I=!1;ka=0;if(W())if(D="video",U(),d)try{F=d.getVideoData().author}catch(b){(F=a.querySelector(".yt-user-info"))&&(F=F.textContent.trim())}else F="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||
/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(D="channel",Ga(),d)try{F=d.getVideoData().author}catch(b){(F=a.querySelector("h1.branded-page-header-title"))&&(F=F.textContent.trim())}else F="";if(D&&d){m=d.parentNode;"EMBED"===d.nodeName?(r=!0,spf.dispose(),"video"===D&&Y()&&ob(),a.body.classList.add("flash-player-loaded")):(O=m.querySelector(".ytp-iv-player-content"),g=d.querySelector("video.html5-main-video"),d.hasAttribute("efyt")||(d.setAttribute("efyt",""),d.addEventListener("onAdStateChange",
ub),d.addEventListener("onStateChange",tb),d.addEventListener("onPlaybackRateChange",sb),d.addEventListener("onError",rb)),m.hasAttribute("efyt")||(m.setAttribute("efyt",""),m.addEventListener("mousedown",Sa,!0),m.addEventListener("mouseleave",qb),m.addEventListener("mouseenter",pb),m.addEventListener("wheel",kb),m.addEventListener("click",lb)),c.controlvolume&&g&&!g.hasAttribute("efyt")&&g.addEventListener("contextmenu",ia,!0),c.controlvolume&&O&&!O.hasAttribute("efyt")&&O.addEventListener("contextmenu",
ia,!0),setTimeout(function(){try{g&&c.overridespeeds?(g.playbackRate=n,g.defaultPlaybackRate=n):d.setPlaybackRate(n)}catch(b){}},500));if("video"===D){c.removeads&&0>ya.indexOf(F)&&(r||!r&&1===d.getAdState())?la():c.autopausevideos&&(r||!r&&1===d.getPlayerState())?ta():c.selectquality&&(r?Z():ma());(c.removeads&&0>ya.indexOf(F)||c.removeads&&c.permissions)&&Ia();c.cinemamode?setTimeout(function(){Fa();!c.cinemamodewideplayer&&c.wideplayer&&H("large")},c.cinemamodewideplayer||c.wideplayer?1200:1):
c.wideplayer&&setTimeout(function(){H("large")},1200);y?(y.style.display="",C.style.display=""):mb();c.pinnedplayer&&(db(),a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition));if(c.expanddescription){a.body.classList.add("expanded-description");try{a.querySelector("#action-panel-details button.yt-uix-expander-collapsed-body").addEventListener("click",function(){setTimeout(function(){a.body.classList.remove("expanded-description")},200)})}catch(b){}}if(c.disableautoplay){var h=a.querySelector("input#autoplay-checkbox");
if(h&&h.checked)var e=setInterval(function(){h.checked?h.click():clearInterval(e)},500)}Y()&&setTimeout(function(){try{"block"===window.getComputedStyle(a.querySelector("#player-unavailable"),null).getPropertyValue("display")&&a.querySelector(".playlist-videos-container .playlist-videos-list li.currently-playing").nextElementSibling.querySelector("a.playlist-video").click()}catch(b){}},2E3)}else"channel"===D&&(c.autopausevideos?ta():c.selectquality&&(r?Z():ma()));Ha(r?m:d);c.enablefilters&&g&&(g.style["-webkit-filter"]=
c.filter,g.style.filter=c.filter);try{c.defaultvolume&&!d.hasAttribute("efyt-muted")&&d.setVolume(c.volume),d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",c.removeannotations?0:1)}catch(b){}}};window.EnhancerForYouTube=!0;var G=EnhancerForYouTubeResources,c=EnhancerForYouTubePreferences,B=EnhancerForYouTubeMessages,x=a.querySelector("#page"),m,O,d,g,C,y,k,w,R,Xa,z,Qa,E,S,da,V=a.hidden,P,Q,qa,ra,N,La,ab,r,Da,ua,bb,cb,D,aa,fb,Ma,ha,
hb,M,q,A,J,wa,ka=0,ba,I,F,ya=""!==c.whitelist?c.whitelist.split(","):[],n=c.speed,za,ca;(new MutationObserver(function(h){h.forEach(function(e){if(null!==e.addedNodes)for(var b=e.addedNodes.length-1;0<=b;b--)if(!r&&e.addedNodes[b].id&&("movie_player"===e.addedNodes[b].id||"c4-player"===e.addedNodes[b].id)){if("EMBED"===e.addedNodes[b].nodeName){try{d.stopVideo()}catch(f){}m=e.addedNodes[b].parentNode;Ha(m);k&&(k.querySelector(".speed").classList.add("not-allowed"),k.querySelector(".filters").classList.add("not-allowed"))}ea()}else if("VIDEO"===
e.addedNodes[b].nodeName&&g&&g!=d.querySelector("video.html5-main-video"))g=e.addedNodes[b],c.controlvolume&&(g.addEventListener("contextmenu",ia,!0),g.setAttribute("efyt","")),setTimeout(function(){ea();try{g&&c.overridespeeds?(g.playbackRate=n,g.defaultPlaybackRate=n):d.setPlaybackRate(n)}catch(f){}},650);else if(e.addedNodes[b].id&&"comment-section-renderer"===e.addedNodes[b].id&&c.newestcomments&&!za)setTimeout(function(){try{a.querySelector(".comment-section-sort-menu button.yt-uix-menu-trigger").click()}catch(f){}},
200);else if("IFRAME"===e.addedNodes[b].nodeName&&e.addedNodes[b].classList.contains("comment-section-sort-menu-mask")&&c.newestcomments&&!za)try{a.querySelector('button.comment-section-sort-menu-item[data-menu_name="newest-first"]').click(),za=!0}catch(f){}})})).observe(a.body,{childList:!0,subtree:!0});window.addEventListener("spfrequest",function(c){r&&(c.preventDefault(),a.location.href=c.detail.url);clearInterval(Ma);clearInterval(aa);za=P=Q=!1;V=a.hidden;y&&(y.style.display="none",C.style.display=
"none",z&&0<z[0].children.length&&(clearInterval(ha),k.querySelector("i.loop").parentNode.classList.remove("active"),z.slider("destroy"),z[0].style.display="none"));a.body.classList.remove("enhancer-for-youtube-pinned-player");try{0>c.detail.url.indexOf("/watch?")&&(pa(),H("default")),d.classList.remove("ads-removed")}catch(e){}});window.addEventListener("spfdone",function(c){a.addEventListener("keydown",Va,!0);V||(Q=!1);ea();a.body.classList.contains("enhancer-for-youtube-wide-player")&&setTimeout(function(){window.dispatchEvent(new Event("resize"))},
1E3)});if(a.querySelector("video.html5-main-video")||a.querySelector("#movie_player"))if(ea(),V&&c.autopausevideos&&(!Y()||Y()&&!c.ignoreplaylists))try{c.disablepreloading&&d.stopVideo(),d.isMuted()||(d.setAttribute("efyt-muted",d.getVolume()),d.mute(),d.setVolume(0))}catch(h){}V&&a.addEventListener("visibilitychange",function e(){a.removeEventListener("visibilitychange",e);t||ea();c.autopausevideos&&setTimeout(function(){try{d.hasAttribute("efyt-muted")&&na()}catch(b){}},500)});window.addEventListener("load",
function b(){window.removeEventListener("load",b);setTimeout(function(){t||ea()},250)});c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));if("default"!==c.theme){var T=a.head.querySelector("#enhancer-for-youtube-theme-variables"),L=a.head.querySelector("#enhancer-for-youtube-theme");L&&L.href&&0>L.href.indexOf("classic")&&(L.href=G+"/vendor/themes/youtube-deep-dark.classic.css");L?T&&0>T.href.indexOf(c.theme)&&(T.href=G+
"/vendor/themes/"+c.theme):"custom"===c.theme?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):(T=a.createElement("link"),T.id="enhancer-for-youtube-theme-variables",T.rel="stylesheet",T.href=G+"/vendor/themes/"+c.theme,a.head.appendChild(T),L=a.createElement("link"),L.id="enhancer-for-youtube-theme",L.rel="stylesheet",L.href=G+"/vendor/themes/youtube-deep-dark.classic.css",a.head.appendChild(L))}a.addEventListener("efyt-pause-video",function(a){try{d.pauseVideo()}catch(f){}});
a.addEventListener("efyt-preference-changed",function(b){var f=JSON.parse(b.detail);b=f.value;switch(f.name){case "autofocusevents":case "autopausevideos":case "controlvolumemousebutton":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "permissions":case "removeads":case "reversemousewheeldirection":case "speedvariation":case "toolbartooltips":case "volumevariation":c[f.name]=b;break;
case "backgroundcolor":c.backgroundcolor=b;C&&(C.style.backgroundColor=b);break;case "backgroundopacity":c.backgroundopacity=b;C&&(C.style.opacity=b/100);break;case "cinemamode":c.cinemamode=b;W()&&(b?Fa():pa());break;case "cinemamodewideplayer":c.cinemamodewideplayer=b;W()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(b?H("large"):H("default"));break;case "controlvolume":c.controlvolume=b;if(m)m[b?"addEventListener":"removeEventListener"]("mousedown",Sa,!0);g&&(g[b?"addEventListener":
"removeEventListener"]("contextmenu",ia,!0),b?g.setAttribute("efyt",""):g.removeAttribute("efyt"));O&&(O[b?"addEventListener":"removeEventListener"]("contextmenu",ia,!0),b?O.setAttribute("efyt",""):O.removeAttribute("efyt"));break;case "customtheme":if("default"!==c.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme-variables"))}catch(l){}f=a.createElement("style");f.type="text/css";f.id="enhancer-for-youtube-theme";
f.textContent=b;a.head.appendChild(f);Oa(b);break;case "defaultvolume":c.defaultvolume=b;try{b&&d.setVolume(c.volume)}catch(l){}break;case "enablefilters":c.enablefilters=b;try{g.style["-webkit-filter"]=b?c.filter:"",g.style.filter=b?c.filter:""}catch(l){}break;case "executescript":c.executescript=b;c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));break;case "expanddescription":c.expanddescription=b;try{a.querySelector("#action-panel-details button.yt-uix-expander"+
(b?"-collapsed":"")+"-body").click()}catch(l){}break;case "filter":c.filter=b;if(!a.hidden)try{g.style["-webkit-filter"]=b,g.style.filter=b,k.querySelector("i.filters").parentNode.classList.add("active")}catch(l){}break;case "message":c.message=b;Aa();break;case "pinnedplayer":c.pinnedplayer=b;m&&m.removeAttribute("io");if(b)a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition),W()&&db();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",c.pinnedplayersize,c.pinnedplayerposition),
La.disconnect()}catch(l){}break;case "pinnedplayerposition":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayerposition);c.pinnedplayerposition=b;break;case "pinnedplayersize":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayersize);c.pinnedplayersize=b;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":c[f.name]=b;if("quality1"===f.name||c.selectquality)b=Date.now(),localStorage["yt-player-quality"]='{"data":"'+c.quality1+'","expiration":'+
(b+2592E6)+',"creation":'+b+"}";D&&c.selectquality&&(I=!1,r?Z():ma());break;case "removeannotations":c.removeannotations=b;try{d[b?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",b?0:1)}catch(l){}break;case "slideeffect":c.slideeffect=b;if(k)k.classList[b?"add":"remove"]("slide-effect");break;case "speed":c.speed=n=b;try{0>[.25,.5,1,1.25,1.5,1.75,2].indexOf(b)?(g.playbackRate=b,g.defaultPlaybackRate=b):d.setPlaybackRate(b)}catch(l){}break;case "theatermode":c.theatermode=
b;if(W())try{b?d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]').parentNode.parentNode.click():d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]').parentNode.parentNode.click()}catch(l){}break;case "theme":f=a.head.querySelector("#enhancer-for-youtube-theme-variables");var p=a.head.querySelector("#enhancer-for-youtube-theme");try{"custom"===c.theme?(a.head.removeChild(p),p=!1):"default"===
c.theme||"custom"!==b&&"default"!==b||(a.head.removeChild(p),a.head.removeChild(f)),c.theme=b,"custom"===b?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):"default"!==b&&(f?f.href=G+"/vendor/themes/"+b:(f=a.createElement("link"),f.id="enhancer-for-youtube-theme-variables",f.rel="stylesheet",f.href=G+"/vendor/themes/"+b,a.head.appendChild(f)),p||(p=a.createElement("link"),p.id="enhancer-for-youtube-theme",p.rel="stylesheet",p.href=G+"/vendor/themes/youtube-deep-dark.classic.css",
a.head.appendChild(p)))}catch(l){}Oa();break;case "toolbarbuttons":c.toolbarbuttons=b;k&&Aa();break;case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbarcoloractive":case "toolbaropacity":c[f.name]=b;eb();break;case "transparency":c.transparency=b;if(k)k.classList[b?"add":"remove"]("transparency");break;case "volume":c.volume=b;try{d.setVolume(b)}catch(l){}break;case "whitelist":ya=""!==b?b.split(","):[];break;case "wideplayer":c.wideplayer=b;W()&&(b?H("large"):
a.body.classList.contains("enhancer-for-youtube-wide-player")&&H("default"));break;case "wideplayerviewport":(c.wideplayerviewport=b,b)?b&&ua&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),setTimeout(function(){d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},
80))):(a.body.classList.remove("viewport","_viewport_"),a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.scrollTo(window.scrollX,0))}});window.addEventListener("error",function(b){setTimeout(function(){r||!d||d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||a.documentElement.hasAttribute("youtube-flash-player")?3E3:1)});window.addEventListener("resize",function(a){clearTimeout(hb);hb=setTimeout(Ea,500)});a.addEventListener("keydown",
function(a){27===a.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&C&&C.click()});var Na;"onfullscreenchange"in a?Na="fullscreenchange":"onmozfullscreenchange"in a&&(Na="mozfullscreenchange");a.addEventListener(Na,function(b){setTimeout(function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.dispatchEvent(new Event("resize"))},500)})}else if(EnhancerForYouTubePreferences.message){var t=a.createElement("link");t.rel="stylesheet";t.href=EnhancerForYouTubeResources+"/youtube.css";
a.head.appendChild(t);var fa=a.createElement("div"),X=a.createElement("i");fa.id="page-reload-required";fa.textContent=EnhancerForYouTubeMessages.page_reload_required;X.className="refresh";X.addEventListener("click",function(){a.location.reload()});fa.appendChild(X);X=a.createElement("i");X.className="close";X.addEventListener("click",function(){fa.style.display="none"});fa.appendChild(X);a.body.appendChild(fa)}})(document);