/*
##
##	Enhancer for YouTube™ | Chrome Extension
##	========================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(a){if(!window.EnhancerForYouTube){var Ta=function(e){q&&"yt-navigate-start"===e.type&&(a.location.href=e.detail.url);clearInterval(Aa);clearInterval(Z);P=Q=!1;U=a.hidden;w&&(w.style.display="none",x.style.display="none",y&&0<y[0].children.length&&(clearInterval(ia),k.querySelector("i.loop").parentNode.classList.remove("active"),y.slider("destroy"),y[0].style.display="none"));a.body.classList.remove("enhancer-for-youtube-pinned-player");if(K&&c.newestcomments){var h=K.querySelector("yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type");
h&&"yt-navigate-start"===e.type?h.removeAttribute("efyt"):h&&"yt-history-load"===e.type&&h.setAttribute("efyt","")}try{a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&("yt-history-load"===e.type||"yt-navigate-start"===e.type&&"watch"!==e.detail.pageType)&&qa(),d.classList.remove("ads-removed")}catch(b){}},Ua=function(a){var e;"undefined"===typeof a&&(e=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:e?
e.customtheme:a,theme:c.theme}))},Ba=function(a){var c=a.querySelector("yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type");!c||c.hasAttribute("efyt")||c.hasAttribute("aria-selected")&&"false"!==c.getAttribute("aria-selected")?c||setTimeout(Ba,1E3,a):(c.setAttribute("efyt",""),a.querySelector("yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type").click())},Da=function(c){try{var e=c||a.querySelector("ytd-compact-autoplay-renderer");if(e){var b=e.querySelector("#head > paper-toggle-button#toggle"),
d=e.querySelector("#head > paper-toggle-button#improved-toggle");(b.checked||b.active)&&b.click();(d.checked||d.active)&&d.click();Ca=!0;t()}else setTimeout(Da,2E3)}catch(v){}},Ea=function(){if(k){for(var a=k.querySelectorAll("li"),d=c.toolbarbuttons.split(","),b=a.length-1;0<=b;b--)a[b].classList[-1<d.indexOf(a[b].dataset.name)?"remove":"add"]("hidden");k.querySelector('li[data-name="message"]').classList[c.message?"remove":"add"]("hidden");""!==c.toolbarbuttons||c.message?(w.classList.remove("hidden"),
Va()):w.classList.add("hidden")}},qb=function(){ra();if(0===y[0].children.length){var a=r;y.slider({animate:"slow",range:!0,min:0,max:L,values:[r,z],start:function(c,b){a=r},slide:function(a,b){r=b.values[0];z=b.values[1];ra()},stop:function(c,b){r===L?(r=L-1,Fa(),ra()):z===r&&(z=r+1,Fa(),ra());a!==r&&d.seekTo(r)}})}else Fa();y.show();w.classList.add("extended")},Fa=function(){y.slider("values",[r,z])},ra=function(){Wa[0].textContent=Ga(r)+" / "+Ga(z)},Xa=function(a){if(a.classList.contains("active"))clearInterval(ia),
a.classList.remove("active"),y.hide(),w.classList.remove("extended"),g&&(g.loop=!1);else{a.classList.add("active");0===$("#enhancer-for-youtube-slider",k).length&&(y=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(k),Wa=$("<div />").addClass("start-end").appendTo(k));L=r=z=!1;var c=0,b=aa();ia=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?L?!b&&d.getCurrentTime()>=z?d.seekTo(r):b||0!==d.getPlayerState()?(b&&!g&&L===z&&2>L-d.getCurrentTime()||b&&L!==z&&d.getCurrentTime()>=
z)&&d.seekTo(r):d.playVideo():(L=z=parseInt(d.getDuration(),10),r=0,"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&(r=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,z=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):z),g&&(g.loop=!0),c=0,qb()):(c++,V())}catch(f){15<c&&clearInterval(ia),d=!1,g&&(g.loop=!1)}},1E3)}},Ga=function(a){a=Number(a);var c=Math.floor(a/3600),b=Math.floor(a%3600/60);a=Math.floor(a%3600%60);return(0<c?c+":":"")+(0<b?
(0<c&&10>b?"0":"")+b+":":"0:")+(10>a?"0":"")+a},Ia=function(){a.body.classList.contains("no-scroll")||A&&A.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar")||a.documentElement.hasAttribute("fullscreen")||(a.body.classList.remove("enhancer-for-youtube-pinned-player"),a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_")),window.scrollTo(0,0),a.body.classList.add("enhancer-for-youtube-cinema-mode"),a.addEventListener("keydown",
Ha),parseInt(16/9*(a.documentElement.clientHeight-56-29),10)>a.documentElement.clientWidth&&a.body.classList.add("_overflow-auto"),c.cinemamodewideplayer&&M("large"),0<=c.autofocusevents.indexOf("cinema")&&t(),k&&k.querySelector("i.cinema").parentNode.classList.add("active"))},qa=function(){a.body.classList.contains("no-scroll")||A&&A.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar")||a.documentElement.hasAttribute("fullscreen")||(a.removeEventListener("keydown",Ha),a.body.classList.remove("enhancer-for-youtube-cinema-mode",
"_overflow-auto"),!c.wideplayer&&c.cinemamodewideplayer&&a.body.classList.contains("enhancer-for-youtube-wide-player")?M("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),c.wideplayerviewport&&ja&&a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY))),0<=c.autofocusevents.indexOf("cinema")&&t(),k&&k.querySelector("i.cinema").parentNode.classList.remove("active"))},
ka=function(a){P=!0;if(c.controlvolumemousebutton&&sa)return a.stopPropagation(),a.preventDefault(),ta=sa=!1},Ya=function(a){P=!0;2===a.button&&c.controlvolumemousebutton&&(ta=!0)},ba=function(){var a=[c.quality1,c.quality2,c.quality3,c.quality4],h=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||("video"===D?V():Ja()),-1!==d.getPlayerState()){for(var c=0,e=!1,g,k=d.getAvailableQualityLevels();c<a.length&&!e;c++)for(var n in k)if(a[c]===k[n]){e=a[c];break}g=e?e:"auto";g!==d.getPlaybackQuality()?
H||(H=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(g),d.playVideo()):d.setPlaybackQuality(g)):g===d.getPlaybackQuality()&&(H=!0,clearInterval(h),clearTimeout(b))}}catch(ua){d=!1}},500),b=setTimeout(function(){clearInterval(h)},3E4)},ma=function(e){d||V();if(d&&d.hasAttribute("flashvars")){clearInterval(ia);clearInterval(Z);k&&y&&0<y[0].children.length&&(k.querySelector("i.loop").parentNode.classList.remove("active"),y.slider("destroy"),y[0].style.display="none");var h="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
b=function(a){for(var b=h.length-1;0<=b;b--)if(a===h[b])return!0;return!1},f=d.getAttribute("flashvars"),v=d.cloneNode(!0);f=f.split("&");for(var m=[],B,l,ua=0;ua<f.length;ua++)B=f[ua].split("="),l=B[0],B=B[1],b(l)||m.push(l+"="+B);b=m.join("&");0>b.indexOf("enablejsapi")&&(b+="&enablejsapi=1");0>b.indexOf("iv_load_policy")&&(b+="&iv_load_policy=1");0>b.indexOf("autoplay")&&(b+="&autoplay=1");c.removeannotations&&(b=b.replace("iv_load_policy=1","iv_load_policy=3"));v.setAttribute("flashvars",b);n.textContent=
"";n.appendChild(v);Ka(n);H=!1;c.autopausevideos&&!c.disablepreloading?va():c.selectquality&&ba()}else if(d){if(e||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(ca)return;try{Number.isFinite(g.duration)?7<d.getDuration()-g.duration&&(ca=!0,(v=d.querySelector("button.ytp-ad-skip-button"))?v.click():(g.currentTime=g.duration-.5,setTimeout(function(){var b=d.querySelector("button.ytp-ad-skip-button");b&&b.click()},2E3)),la=0,c.overridespeeds?g.playbackRate=
p:d.setPlaybackRate(p)):setTimeout(function(){ma(e)},50)}catch(Za){if(!g||(0<Za.message.indexOf("currentTime")||"IndexSizeError"===Za.message)&&g!=a.querySelector("video.html5-main-video"))return}}else La();0<=c.autofocusevents.indexOf("ads")&&t()}else setTimeout(function(){ma(e)},100)},La=function(){d.classList.add("ads-removed")},na=function(){try{"object"===typeof da&&(da.disconnect(),da=void 0);var a=d.querySelector("button.ytp-settings-button"),h=d.querySelector("div.ytp-settings-menu");if(!H&&
a&&h){da=new MutationObserver(function(b){b.forEach(function(b){if(null!==b.addedNodes)for(var a=b.addedNodes.length-1;0<=a;a--)if("DIV"===b.addedNodes[a].nodeName&&b.addedNodes[a].classList.contains("ytp-menuitem")&&/\d{3,4}[p,s]/.test(b.addedNodes[a].textContent))b.addedNodes[a].click();else if("DIV"===b.addedNodes[a].nodeName&&b.addedNodes[a].classList.contains("ytp-quality-menu")){a=0;var e=!1,d={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres","4320s 8K":"highres",
"2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160","2160p 4K":"hd2160","2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60 HD":"hd720","720p50 HD":"hd720","720p48 HD":"hd720","720p HD":"hd720",
"720s HD":"hd720","480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},f=b.addedNodes[a].querySelectorAll("div.ytp-menuitem");0<f.length&&[c.quality1,c.quality2,c.quality3,c.quality4].forEach(function(b){if(!e){for(;a<f.length;a++)if(b===d[f[a].textContent]){f[a].click();e=!0;break}a=0}});e||f[0].click();H=!0;h.classList.remove("hidden");da.disconnect();t()}})});da.observe(h,{childList:!0,subtree:!0});for(var b=h.querySelectorAll("div.ytp-menuitem"),
f,g=b.length-1;0<=g;g--)if(/\d{3,4}[p,s]/.test(b[g].textContent)){f=b[g];break}h.classList.add("hidden");setTimeout(function(){h.classList.remove("hidden")},2500);f?(a.click(),f.click()):a.click()}else if(!H){var m=d.getAvailableQualityLevels();0<=m.indexOf(c.quality1)?d.setPlaybackQuality(c.quality1):0<=m.indexOf(c.quality2)?d.setPlaybackQuality(c.quality2):0<=m.indexOf(c.quality3)?d.setPlaybackQuality(c.quality3):0<=m.indexOf(c.quality4)&&d.setPlaybackQuality(c.quality4)}}catch(B){}},M=function(e){if(!(a.body.classList.contains("no-scroll")||
A&&A.hasAttribute("fullscreen")||a.documentElement.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar"))){try{var h=a.body.classList.contains("enhancer-for-youtube-wide-player");A&&!oa&&(oa=A.hasAttribute("theater")&&!h);if("large"===e||!e&&!h){$a||ab();(G=d.querySelector(".ytp-size-button"))&&G.removeEventListener("click",Ma);if(A&&!A.hasAttribute("theater")&&G)G.click();else{var b=d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]');
if(b)b.parentNode.parentNode.click();else if(!G)return}a.body.classList.add("enhancer-for-youtube-wide-player");G&&G.addEventListener("click",Ma);a.addEventListener("keydown",Na);c.wideplayerviewport&&ja&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){d&&window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80)));setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})}))},250)}else if("default"===e||!e&&h){a.removeEventListener("keydown",Na);if(!oa&&A&&A.hasAttribute("theater"))if(G=d.querySelector(".ytp-size-button"))G.click();else{var f=d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');f?f.parentNode.parentNode.click():(A.removeAttribute("theater-requested_"),a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})})))}oa=!1;setTimeout(function(){a.body.classList.remove("enhancer-for-youtube-wide-player","viewport","_viewport_")},100)}}catch(v){}0<=c.autofocusevents.indexOf("size")&&t();window.dispatchEvent(new Event("resize"))}},bb=function(){G&&G.removeEventListener("click",Ma);a.removeEventListener("keydown",Na);oa=!1;setTimeout(function(){a.body.classList.remove("enhancer-for-youtube-wide-player",
"viewport","_viewport_")},100);setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})}))},500)},Ma=function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&bb()},Na=function(c){84===c.keyCode&&a.body.classList.contains("enhancer-for-youtube-wide-player")&&"INPUT"!==a.activeElement.nodeName&&!a.activeElement.isContentEditable&&bb()},Ha=function(c){27===
c.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&!d.classList.contains("ytp-settings-shown")&&x&&(c=a.querySelector(".ytp-popup.ytp-contextmenu"),c&&0<c.getBoundingClientRect().height||(a.removeEventListener("keydown",Ha),x.click()))},cb=function(c){P=!0;a.removeEventListener("keydown",cb,!0)},va=function(){if(c.ignoreplaylists&&aa()||!c.pauseforegroundtab&&!U&&!a.hidden)Q=!0,d.hasAttribute("efyt-muted")&&pa(),c.selectquality&&(q?ba():na()),!c.pausevideos||a.hidden||N||(N=!0,a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){N=!1},1E3));else{clearInterval(Z);try{if(c.disablepreloading&&"video"===D&&U)d.stopVideo(),Q=!0,d.hasAttribute("efyt-muted")&&pa(),d.addEventListener("onStateChange",function m(b){if(1===b){d.removeEventListener("onStateChange",m);c.selectquality&&q&&ba();try{var e=a.location.href.match(/&t=(\d+)s?/);e&&d.seekTo(parseInt(e[1],10));d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded",
c.removeannotations?0:1)}catch(Cb){}}});else{d.pauseVideo();Q=!0;var e=a.location.href.match(/&t=(\d+)s?/);e?d.seekTo(parseInt(e[1],10)):U&&!P&&d.seekTo(0);d.hasAttribute("efyt-muted")&&pa()}}catch(f){var h,b=0;Z=setInterval(function(){try{d&&"function"===typeof d.getPlayerState||(b++,"video"===D?V():Ja()),h=d.getPlayerState(),a.hidden?-1!==h&&c.disablepreloading?d.stopVideo():2===h||c.disablepreloading||d.pauseVideo():-1!==h&&5!==h&&c.pauseforegroundtab&&c.disablepreloading?d.stopVideo():2!==h&&
c.pauseforegroundtab&&!c.disablepreloading?(-1!==h&&5!==h||d.playVideo(),3!==h&&d.pauseVideo()):clearInterval(Z)}catch(v){200<b&&clearInterval(Z),d=!1}},50)}t()}},db=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();p=c.speed;try{c.overridespeeds?g.playbackRate=p:d.setPlaybackRate(p),"I"===a.target.nodeName&&c.toolbartooltips?u.textContent=C.speed+" x"+p:(R.textContent="x"+p,Oa())}catch(h){}0<=c.autofocusevents.indexOf("speed")&&
t()}},Oa=function(){R.setAttribute("style","display:block!important");clearTimeout(eb);eb=setTimeout(function(){R.setAttribute("style","display:none!important")},1500)},Va=function(){w.style.marginLeft="-"+k.getBoundingClientRect().width/2+"px"},I=function(a,d){a.addEventListener("mouseenter",function(a){c.toolbartooltips&&(u.textContent=d,u.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/2-u.clientWidth/2+"px",u.classList.add("visible"))});a.addEventListener("mouseleave",function(){u.classList.remove("visible")})},
fb=function(){try{E.max=g.duration,E.value=g.currentTime}catch(e){}},wa=function(a){a.preventDefault();if(!q){try{if(c.overridespeeds){var e=g.playbackRate;if(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)e=parseFloat((e-c.speedvariation).toFixed(2)),0>=e&&(e=c.speedvariation),g.playbackRate=e;else if(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)e=parseFloat((e+c.speedvariation).toFixed(2)),g.playbackRate=e}else{var b=d.getAvailablePlaybackRates();
e=d.getPlaybackRate();var f=b.indexOf(e);(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)&&0<f?(e=b[f-1],d.setPlaybackRate(e)):(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)&&f<b.length-1&&(e=b[f+1],d.setPlaybackRate(e))}p=e;"I"===a.target.nodeName&&c.toolbartooltips?u.textContent=C.speed+" x"+e:(R.textContent="x"+e,Oa())}catch(v){}0<=c.autofocusevents.indexOf("speed")&&t()}},rb=function(a){if(a.ctrlKey)wa(a);else if(c.controlvolume&&
(c.controlvolumemousebutton&&ta||!c.controlvolumemousebutton)){a.preventDefault();try{var e=d.getVolume();!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY?(e-=c.volumevariation,0>e&&(e=0)):(e+=c.volumevariation,100<e&&(e=100),d.isMuted()&&d.unMute());sa=!0;d.setVolume(e);R.textContent=e;Oa();c.defaultvolume&&(c.volume=e);var b=Date.now();a=0<e?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","expiration":'+(b+2592E6)+
',"creation":'+b+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","creation":'+b+"}"}catch(f){}}},sb=function(a){a.shiftKey?gb(a):a.ctrlKey&&db(a)},gb=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var d=""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?!1:!0;g.style["-webkit-filter"]=d?"":c.filter;g.style.filter=d?"":c.filter;k.querySelector("i.filters").parentNode.classList[d?"remove":"add"]("active")}catch(b){}0<=
c.autofocusevents.indexOf("filters")&&t()}},Ka=function(c){c.querySelector("#enhancer-for-youtube-player-info")||(a.querySelector("#enhancer-for-youtube-player-info")||(R=a.createElement("div"),R.id="enhancer-for-youtube-player-info"),c.appendChild(R))},hb=function(c){var e=a.location.href.match(/&?v=([^&\?]+)/)[1]+"?autoplay=1",b=a.location.href.match(/&?list=([^&\?]+)/);b&&(e+="&list="+b[1]);try{d.pauseVideo();var f=d.getCurrentTime();f&&(e+="&start="+parseInt(f,10));c&&d.stopVideo()}catch(v){}a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"detach",params:e})}))},Pa=function(a){if(c.toolbartooltips){var d="";try{d=" x"+g.playbackRate}catch(b){}u.textContent=C.speed+d;u.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/2-u.clientWidth/2+"px";u.classList.add("visible")}},tb=function(){if(!w){x=a.createElement("div");w=a.createElement("div");k=a.createElement("div");u=a.createElement("div");var e=a.createDocumentFragment(),h=a.createElement("ul"),b=a.createElement("li"),f=
a.createElement("i");x.id="enhancer-for-youtube-background";x.style.visibility="hidden";x.addEventListener("click",function(){qa()});e.appendChild(x);w.id="enhancer-for-youtube-toolbar-wrapper";k.id="enhancer-for-youtube-toolbar";u.id="enhancer-for-youtube-tooltip";e.appendChild(u);k.style.visibility="hidden";c.transparency&&k.classList.add("transparency");c.slideeffect&&k.classList.add("slide-effect");b.dataset.name=f.className="message";b.appendChild(f);f=a.createElement("i");f.className="badge";
b.appendChild(f);b.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-message"})}))});I(b,C.message);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="clean";b.appendChild(f);b.addEventListener("click",function(){xa=!0;ca=!1;ma()});b.addEventListener("contextmenu",function(a){a.preventDefault();d||V();try{var b=d.getAttribute("annotations-module-loaded");d["1"===b?"unloadModule":
"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===b?0:1);0<=c.autofocusevents.indexOf("annotations")&&t()}catch(Eb){}return!1});I(b,C.remove_ads);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="cinema";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?qa():Ia()});I(b,C.cinema_mode);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=
f.className="resize";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),M())});b.addEventListener("contextmenu",function(b){b.preventDefault();b=a.querySelector("ytd-masthead");try{window.scrollTo(window.scrollX,n.getBoundingClientRect().top-
(a.body.classList.contains("viewport")?0:b?b.clientHeight:56)+window.scrollY)}catch(Db){}return!1});I(b,C.resize_player);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="detach";b.appendChild(f);b.addEventListener("click",function(){hb(!1)});b.addEventListener("contextmenu",function(a){a.preventDefault();hb(!0);return!1});I(b,C.detach_player);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="boost";b.appendChild(f);
b.addEventListener("click",function(){if(g){if(!ea){var a=new (window.AudioContext||window.webkitAudioContext),b=a.createMediaElementSource(g);ea=a.createGain();b.connect(ea);ea.connect(a.destination)}this.classList.contains("active")?(ea.gain.value=1,this.classList.remove("active")):(ea.gain.value=3,this.classList.add("active"));0<=c.autofocusevents.indexOf("boost")&&t()}});I(b,C.boost_volume);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="loop";b.appendChild(f);
b.addEventListener("click",function(){if(ib)Xa(this);else{ib=!0;l=a.createElement("link");l.rel="stylesheet";l.href=J+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(l);var b=this,d=a.createElement("script");d.src=J+"/vendor/jquery/jquery-3.3.1.min.js";d.onload=function(){d=a.createElement("script");d.src=J+"/vendor/jquery/jquery-ui.min.js";d.onload=function(){Xa(b)};a.head.appendChild(d)};a.head.appendChild(d)}0<=c.autofocusevents.indexOf("loop")&&t()});I(b,C.loop_video);h.appendChild(b);b=
a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="slowdown";b.appendChild(f);f=a.createElement("i");f.className="minus";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",function(){wa({target:{nodeName:"I"},deltaY:1,preventDefault:function(){}})});b.addEventListener("mouseenter",Pa);b.addEventListener("mouseleave",function(){u.classList.remove("visible")});h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"speed";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",db);b.addEventListener("wheel",wa);b.addEventListener("mouseenter",Pa);b.addEventListener("mouseleave",function(){u.classList.remove("visible")});h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="speedup";b.appendChild(f);f=a.createElement("i");f.className="plus";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",function(){wa({target:{nodeName:"I"},
deltaY:-1,preventDefault:function(){}})});b.addEventListener("mouseenter",Pa);b.addEventListener("mouseleave",function(){u.classList.remove("visible")});h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="filters";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",gb);b.addEventListener("touchstart",function(b){if(this.hasAttribute("ui"))a.querySelector("#enhancer-for-youtube-filters").classList[this.classList.contains("active")?"add":
"remove"]("hidden");else a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})}))});b.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})})));return!1});I(b,C.filters);h.appendChild(b);b=a.createElement("li");
f=a.createElement("i");b.dataset.name=f.className="script";b.appendChild(f);b.addEventListener("click",function(){t();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}))});I(b,C.custom_script);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="options";b.appendChild(f);b.addEventListener("click",function(){t();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-options"})}))});
I(b,C.options);h.appendChild(b);k.appendChild(h);w.appendChild(k);e.appendChild(w);E=a.createElement("progress");E.id="enhancer-for-youtube-progress";E.max=1;E.value=0;E.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth));t()});E.addEventListener("mouseenter",function(){S.classList.add("visible")});E.addEventListener("mouseleave",function(){S.classList.remove("visible")});E.addEventListener("mousemove",function(a){g&&(S.textContent=
Ga(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),S.style.left=a.pageX-S.getBoundingClientRect().width/2+"px")});e.appendChild(E);S=a.createElement("div");S.id="enhancer-for-youtube-progress-tooltip";e.appendChild(S);h=a.createElement("div");h.id="enhancer-for-youtube-unpin-player";h.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});e.appendChild(h);a.body.appendChild(e);setTimeout(function(){Ea();Va();x.style.visibility="";k.style.visibility=
""},500);if((e=d.querySelector(".ytp-right-controls"))&&!e.querySelector(".efy-ytp-keyboard-shortcuts")){var v,m=a.createElement("div");h=a.createElement("div");b=a.createElement("span");var B=a.createElement("button");f=a.createElementNS("http://www.w3.org/2000/svg","svg");var p=a.createElementNS("http://www.w3.org/2000/svg","path"),r=e.querySelector('button:not([style*="display"])');b.className="ytp-tooltip-text";b.textContent=C.keyboard_shortcuts+" \ud83d\uddd7";h.appendChild(b);h.className="ytp-tooltip-text-wrapper";
m.appendChild(h);m.className="ytp-bottom";m.style.display="none";d.appendChild(m);B.className="ytp-button efy-ytp-keyboard-shortcuts";B.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"keyboard-shortcuts"})}))});B.addEventListener("mouseenter",function(a){r.dispatchEvent(new Event("mouseover"));r.dispatchEvent(new Event("mouseout"));v||(v=d.querySelector(".ytp-tooltip"));v&&""!==v.style.top&&(m.classList.add("ytp-tooltip"),
m.style.display="block",m.style.top=v.style.top,m.style.left=B.offsetLeft+a.target.getBoundingClientRect().width-m.getBoundingClientRect().width/2+"px")});B.addEventListener("mouseleave",function(){m.style.display="none";m.classList.remove("ytp-tooltip")});f.setAttributeNS(null,"version","1.1");f.setAttributeNS(null,"viewBox","0 0 36 36");f.setAttributeNS(null,"height","100%");f.setAttributeNS(null,"width","100%");p.setAttributeNS(null,"d","m26 11h-16c-1.1 0-1.99.9-1.99 2l-.01 10c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2v-10c0-1.1-.9-2-2-2zm-9 3h2v2h-2zm0 3h2v2h-2zm-3-3h2v2h-2zm0 3h2v2h-2zm-1 2h-2v-2h2zm0-3h-2v-2h2zm9 7h-8v-2h8zm0-4h-2v-2h2zm0-3h-2v-2h2zm3 3h-2v-2h2zm0-3h-2v-2h2z");
p.setAttributeNS(null,"fill","#fff");B.appendChild(f);f.appendChild(p);e.insertBefore(B,e.firstChild)}}},ab=function(){var c=a.documentElement.clientWidth,d=a.documentElement.clientHeight;if(c!==jb||d!==kb){jb=c;kb=d;var b=window.innerWidth,f=a.querySelector("ytd-masthead");f=f?f.getBoundingClientRect().height:56;var g=k?k.getBoundingClientRect().height:29;if(parseInt(16/9*(d-f-g),10)>c){f=c;g=parseInt(f/(16/9),10);d=f;var m=g;ja=!1}else g=parseInt(d-f-g,10),f=parseInt(16/9*g,10),b-=b-f,m=window.screen.height===
d?d-12:d,d=parseInt(16/9*m,10),ja=!0;var n=parseInt(b/(16/9),10);var l=parseInt((c-f)/2,10);c=parseInt((c-d)/2,10);var p=a.createElement("style");p.type="text/css";p.textContent="body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
g+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
m+"px !important}body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+f+"px !important;left:"+l+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
d+"px !important;left:"+c+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
n+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+b+"px !important}";a.head.appendChild(p);$a=!0}},lb=function(){window.IntersectionObserver&&!n.hasAttribute("io")&&(n.setAttribute("io",1),Qa=new IntersectionObserver(function(e){if((0===
e[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&0<window.scrollY||0<e[0].intersectionRatio&&.12>e[0].intersectionRatio)&&window.scrollY>n.offsetHeight-100&&W()){if(!d||!d.classList.contains("ended-mode")){g&&g.addEventListener("timeupdate",fb);a.body.classList.add("enhancer-for-youtube-pinned-player");try{g.style.top=""}catch(h){}0<=c.autofocusevents.indexOf("pin")&&t()}}else 0!==e[0].intersectionRatio&&(g&&g.removeEventListener("timeupdate",fb),a.body.classList.remove("enhancer-for-youtube-pinned-player"),
window.dispatchEvent(new Event("resize")),q||ub())},{threshold:.12}),Qa.observe(n))},ub=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var c=n.clientHeight,h=g.clientHeight;d.clientHeight!==c?(d.style.width=n.clientWidth,d.style.height=c,d.style.width="",d.style.height=""):h!==c&&(g.style.width=n.clientWidth,g.style.height=c,g.style.top="")}}catch(b){}},50)},vb=function(){Aa=setInterval(function(){try{if("function"!==typeof d.getPlayerState&&
V(),0===d.getPlayerState()&&(clearInterval(Aa),!k.querySelector("i.loop").parentNode.classList.contains("active"))){var c=a.querySelector("ytd-watch-flexy ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]");if(c){var h=c.nextElementSibling;h&&(a.location.href=h.querySelector("a").href)}}}catch(b){}},5E3)},Ra=function(){var d=c.backgroundcolor.replace("#",""),h=parseInt(d.substring(0,2),16),b=parseInt(d.substring(2,4),16);d=parseInt(d.substring(4,6),16);l=a.createElement("style");
l.type="text/css";l.textContent="body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player .html5-video-player{background-color:rgba("+h+","+b+","+d+","+c.backgroundopacity/100+")}";a.head.appendChild(l)},pa=function(){d.unMute();d.setVolume(c.defaultvolume?c.volume:parseInt(d.getAttribute("efyt-muted"),10));d.removeAttribute("efyt-muted")},t=function(){try{a.activeElement.blur(),d.focus({preventScroll:!0})}catch(e){}},Ja=function(){d=a.querySelector("#c4-player")},V=function(){d=a.querySelector("#movie_player")},
aa=function(){return 0<a.location.href.indexOf("list=")},W=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/.*\/live/.test(a.location.href)},ya=function(a,c){var b=parseInt(a.slice(1),16),d=0>c?0:255,e=0>c?-1*c:c,h=b>>16,g=b>>8&255;b&=255;return"#"+(16777216+65536*(Math.round((d-h)*e)+h)+256*(Math.round((d-g)*e)+g)+(Math.round((d-b)*e)+b)).toString(16).slice(1)},mb=function(){var d=a.createElement("style"),h=c.toolbarbackgroundcolor.replace("#",
""),b=parseInt(h.substring(0,2),16),f=parseInt(h.substring(2,4),16);h=parseInt(h.substring(4,6),16);d.type="text/css";d.textContent="#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+c.toolbarbackgroundcolor+";border-top:1px solid "+c.toolbarbordercolor+";border-right:1px solid "+c.toolbarbordercolor+";border-left:1px solid "+c.toolbarbordercolor+";color:"+c.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+
c.toolbarcolor+" !important}#enhancer-for-youtube-toolbar li.active i{color:"+c.toolbarcoloractive+" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+c.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+c.toolbarbackgroundcolor+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+ya(c.toolbarbackgroundcolor,-.1)+"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+
ya(c.toolbarbackgroundcolor,-.1)+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+ya(c.toolbarbackgroundcolor,-.15)+";border:1px solid "+ya(c.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+b+","+f+","+h+",0.85)}#enhancer-for-youtube-filters{background-color:"+c.toolbarbackgroundcolor+" !important;border:1px solid "+c.toolbarbordercolor+
" !important;color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+c.toolbarcolor+" !important}";a.head.appendChild(d)},wb=function(){P=!0;nb=setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||a.activeElement.classList.contains("ytp-volume-panel"))&&t()}catch(e){}},3E3)},xb=function(){P=!0;clearInterval(nb);ta=sa=!1},yb=function(a){try{100<=a&&setTimeout(function(){d.nextVideo()},2E3)}catch(h){}},
ob=function(a){1===a&&(d.removeEventListener("onStateChange",ob),g&&c.overridespeeds?g.playbackRate=p:d.setPlaybackRate(p))},zb=function(a){"number"===typeof a&&(p=a)},Ab=function(e){try{c.pausevideos&&!a.hidden&&1===e&&!N&&(c.autopausevideos&&Q||!c.autopausevideos)&&(N=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){N=!1},1E3)),!c.autopausevideos||Q||P||1!==e||va(),c.selectquality&&!H&&1===e&&na(),1===e?ca=!1:
2===e&&(Q=!0),0===e&&"video"===D&&setTimeout(function(){d.classList.contains("ended-mode")&&(E.value=E.max)},500)}catch(h){}},Bb=function(e){try{!c.pausevideos||a.hidden||1!==e||N||c.removeads||(N=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})),setTimeout(function(){N=!1},1E3));c.removeads&&1===e||xa&&1===e?la++:!c.removeads&&1===e&&d.hasAttribute("efyt-muted")&&pa();if(c.removeads&&1===e&&3>la&&0>za.indexOf(F)||xa&&1===e&&3>la)"video"===
D?ma(e):(g.currentTime=g.duration-.5,La());if(0===e||0===d.getAdState())ca=!1,d.addEventListener("onStateChange",ob)}catch(h){}},X=function(){l||(l=a.createElement("link"),l.rel="stylesheet",l.href=J+"/youtube-polymer.css",a.head.appendChild(l),l=a.createElement("style"),l.type="text/css",l.textContent="#enhancer-for-youtube-background{background-color:"+c.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+c.backgroundopacity/100+";visibility:visible}",
a.head.appendChild(l),Ra(),mb());D=d=n=O=g=xa=ca=H=!1;la=0;if(W())if(D="video",V(),d)try{F=d.getVideoData().author}catch(e){(F=a.querySelector("#owner-name.ytd-video-owner-renderer"))&&(F=F.textContent.trim())}else F="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(D=
"channel",Ja(),d)try{F=d.getVideoData().author}catch(e){(F=a.querySelector("h1 #channel-title"))&&(F=F.textContent.trim())}else F="";if(D&&d){n=d.parentNode;"EMBED"===d.nodeName?(q=!0,"video"===D&&aa()&&vb(),a.body.classList.add("flash-player-loaded")):(O=n.querySelector(".ytp-iv-player-content"),g=d.querySelector("video.html5-main-video"),d.hasAttribute("efyt")||(d.setAttribute("efyt",""),d.addEventListener("onAdStateChange",Bb),d.addEventListener("onStateChange",Ab),d.addEventListener("onPlaybackRateChange",
zb),d.addEventListener("onError",yb)),n.hasAttribute("efyt")||(n.setAttribute("efyt",""),n.addEventListener("mousedown",Ya,!0),n.addEventListener("mouseleave",xb),n.addEventListener("mouseenter",wb),n.addEventListener("wheel",rb),n.addEventListener("click",sb)),K&&!K.hasAttribute("efyt")&&(K.setAttribute("efyt",""),K.addEventListener("data-changed",function(a){c.newestcomments&&a.detail.path&&"data.header"===a.detail.path&&setTimeout(Ba,500,a.target)})),c.controlvolume&&g&&!g.hasAttribute("efyt")&&
g.addEventListener("contextmenu",ka,!0),c.controlvolume&&O&&!O.hasAttribute("efyt")&&O.addEventListener("contextmenu",ka,!0),setTimeout(function(){try{g&&c.overridespeeds?(g.playbackRate=p,g.defaultPlaybackRate=p):d.setPlaybackRate(p)}catch(e){}},500));"video"===D?(c.removeads&&0>za.indexOf(F)&&(q||!q&&1===d.getAdState())?ma():c.autopausevideos&&(q||!q&&1===d.getPlayerState())?va():c.selectquality&&(q?ba():na()),(c.removeads&&0>za.indexOf(F)||c.removeads&&c.permissions)&&La(),c.cinemamode?(Ia(),!c.cinemamodewideplayer&&
c.wideplayer&&M("large")):c.wideplayer&&M("large"),w?(w.style.display="",x.style.display=""):tb(),c.pinnedplayer&&(lb(),a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition)),c.expanddescription&&setTimeout(function(){try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#more").click()}catch(e){}},2E3),c.disableautoplay&&!Ca&&Da(),aa()&&setTimeout(function(){try{var c=a.querySelector("ytd-playability-error-supported-renderers");c&&240<=c.getBoundingClientRect().height&&
a.querySelector("ytd-watch-flexy ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]").nextElementSibling.querySelector("a").click()}catch(h){}},2E3)):"channel"===D&&(c.autopausevideos?va():c.selectquality&&(q?ba():na()));Ka(q?n:d);c.enablefilters&&g&&(g.style["-webkit-filter"]=c.filter,g.style.filter=c.filter);try{c.defaultvolume&&!d.hasAttribute("efyt-muted")&&d.setVolume(c.volume),d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",
c.removeannotations?0:1)}catch(e){}}};window.EnhancerForYouTube=!0;var J=EnhancerForYouTubeResources,c=EnhancerForYouTubePreferences,C=EnhancerForYouTubeMessages,A=a.querySelector("ytd-watch-flexy"),K=a.querySelector("ytd-item-section-renderer#sections.ytd-comments"),G,n,O,d,g,x,w,k,u,R,eb,y,Wa,E,S,ea,U=a.hidden,P,Q,Ca,sa,ta,N,Qa,ib,q,$a,ja,jb,kb,D,Z,nb,Aa,ia,pb,L,r,z,oa,xa,la=0,ca,H,F,za=""!==c.whitelist?c.whitelist.split(","):[],p=c.speed,da;(new MutationObserver(function(e){e.forEach(function(e){if(null!==
e.addedNodes)for(var b=e.addedNodes.length-1;0<=b;b--)if(q||!e.addedNodes[b].id||"movie_player"!==e.addedNodes[b].id&&"c4-player"!==e.addedNodes[b].id)if("YTD-WATCH-FLEXY"===e.addedNodes[b].nodeName)A=e.addedNodes[b];else if("VIDEO"===e.addedNodes[b].nodeName&&g&&g!=d.querySelector("video.html5-main-video"))g=e.addedNodes[b],c.controlvolume&&(g.addEventListener("contextmenu",ka,!0),g.setAttribute("efyt","")),setTimeout(function(){X();try{g&&c.overridespeeds?(g.playbackRate=p,g.defaultPlaybackRate=
p):d.setPlaybackRate(p)}catch(f){}},650);else if("YTD-VIDEO-SECONDARY-INFO-RENDERER"===e.addedNodes[b].nodeName&&c.expanddescription)try{e.addedNodes[b].querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#more").click()}catch(f){}else"YTD-ITEM-SECTION-RENDERER"===e.addedNodes[b].nodeName&&e.addedNodes[b].classList.contains("ytd-comments")?(K=e.addedNodes[b],K.setAttribute("efyt",""),K.addEventListener("data-changed",function(a){c.newestcomments&&a.detail.path&&"data.header"===
a.detail.path&&setTimeout(Ba,500,a.target)})):"YTD-COMPACT-AUTOPLAY-RENDERER"===e.addedNodes[b].nodeName&&c.disableautoplay&&!Ca&&Da(e.addedNodes[b]);else if("EMBED"===e.addedNodes[b].nodeName){try{d.stopVideo()}catch(f){}n=e.addedNodes[b].parentNode;Ka(n);k&&(k.querySelector(".speed").classList.add("not-allowed"),k.querySelector(".filters").classList.add("not-allowed"));"complete"===a.readyState&&X()}else"c4-player"===e.addedNodes[b].id&&X()})})).observe(a.body,{childList:!0,subtree:!0});window.addEventListener("yt-history-load",
Ta);window.addEventListener("yt-navigate-start",Ta);window.addEventListener("yt-navigate-finish",function(c){a.addEventListener("keydown",cb,!0);U||(Q=!1);X();a.body.classList.contains("enhancer-for-youtube-wide-player")&&setTimeout(function(){window.dispatchEvent(new Event("resize"))},1E3)});if(a.querySelector("video.html5-main-video")||a.querySelector("#movie_player"))if(X(),U&&c.autopausevideos&&(!aa()||aa()&&!c.ignoreplaylists))try{c.disablepreloading&&d.stopVideo(),d.isMuted()||(d.setAttribute("efyt-muted",
d.getVolume()),d.mute(),d.setVolume(0))}catch(e){}U&&a.addEventListener("visibilitychange",function h(){a.removeEventListener("visibilitychange",h);l||X();c.autopausevideos&&setTimeout(function(){try{d.hasAttribute("efyt-muted")&&pa()}catch(b){}},500)});window.addEventListener("load",function b(){window.removeEventListener("load",b);setTimeout(function(){l||X()},250)});c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));if("default"!==
c.theme){var T=a.head.querySelector("#enhancer-for-youtube-theme-variables"),fa=a.head.querySelector("#enhancer-for-youtube-theme");fa?T&&0>T.href.indexOf(c.theme)&&(T.href=J+"/vendor/themes/"+c.theme):"custom"===c.theme?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):(T=a.createElement("link"),T.id="enhancer-for-youtube-theme-variables",T.rel="stylesheet",T.href=J+"/vendor/themes/"+c.theme,a.head.appendChild(T),fa=a.createElement("link"),
fa.id="enhancer-for-youtube-theme",fa.rel="stylesheet",fa.href=J+"/vendor/themes/youtube-deep-dark.material.css",a.head.appendChild(fa))}a.addEventListener("efyt-pause-video",function(a){try{d.pauseVideo()}catch(f){}});a.addEventListener("efyt-preference-changed",function(b){var f=JSON.parse(b.detail);b=f.value;switch(f.name){case "autofocusevents":case "autopausevideos":case "controlvolumemousebutton":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "permissions":case "removeads":case "reversemousewheeldirection":case "speedvariation":case "toolbartooltips":case "volumevariation":c[f.name]=
b;break;case "backgroundcolor":c.backgroundcolor=b;x&&(x.style.backgroundColor=b);Ra();break;case "backgroundopacity":c.backgroundopacity=b;x&&(x.style.opacity=b/100);Ra();break;case "cinemamode":c.cinemamode=b;W()&&(b?Ia():qa());break;case "cinemamodewideplayer":c.cinemamodewideplayer=b;W()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(b?M("large"):M("default"));break;case "controlvolume":c.controlvolume=b;if(n)n[b?"addEventListener":"removeEventListener"]("mousedown",Ya,!0);g&&
(g[b?"addEventListener":"removeEventListener"]("contextmenu",ka,!0),b?g.setAttribute("efyt",""):g.removeAttribute("efyt"));O&&(O[b?"addEventListener":"removeEventListener"]("contextmenu",ka,!0),b?O.setAttribute("efyt",""):O.removeAttribute("efyt"));break;case "customtheme":if("default"!==c.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme-variables"))}catch(m){}f=a.createElement("style");f.type="text/css";
f.id="enhancer-for-youtube-theme";f.textContent=b;a.head.appendChild(f);Ua(b);break;case "defaultvolume":c.defaultvolume=b;try{b&&d.setVolume(c.volume)}catch(m){}break;case "enablefilters":c.enablefilters=b;try{g.style["-webkit-filter"]=b?c.filter:"",g.style.filter=b?c.filter:""}catch(m){}break;case "executescript":c.executescript=b;c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));break;case "expanddescription":c.expanddescription=
b;try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#"+(b?"more":"less")).click()}catch(m){}break;case "filter":c.filter=b;if(!a.hidden)try{g.style["-webkit-filter"]=b,g.style.filter=b,k.querySelector("i.filters").parentNode.classList.add("active")}catch(m){}break;case "message":c.message=b;Ea();break;case "pinnedplayer":c.pinnedplayer=b;n&&n.removeAttribute("io");if(b)a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition),W()&&lb();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",
c.pinnedplayersize,c.pinnedplayerposition),Qa.disconnect()}catch(m){}break;case "pinnedplayerposition":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayerposition);c.pinnedplayerposition=b;break;case "pinnedplayersize":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayersize);c.pinnedplayersize=b;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":c[f.name]=b;if("quality1"===f.name||c.selectquality)b=Date.now(),localStorage["yt-player-quality"]=
'{"data":"'+c.quality1+'","expiration":'+(b+2592E6)+',"creation":'+b+"}";D&&c.selectquality&&(H=!1,q?ba():na());break;case "removeannotations":c.removeannotations=b;try{d[b?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",b?0:1)}catch(m){}break;case "slideeffect":c.slideeffect=b;if(k)k.classList[b?"add":"remove"]("slide-effect");break;case "speed":c.speed=p=b;try{0>[.25,.5,1,1.25,1.5,1.75,2].indexOf(b)?(g.playbackRate=b,g.defaultPlaybackRate=b):d.setPlaybackRate(b)}catch(m){}break;
case "theatermode":c.theatermode=b;if(W())try{b?d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]').parentNode.parentNode.click():d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]').parentNode.parentNode.click()}catch(m){}break;case "theme":f=a.head.querySelector("#enhancer-for-youtube-theme-variables");var l=a.head.querySelector("#enhancer-for-youtube-theme");try{"custom"===c.theme?(a.head.removeChild(l),
l=!1):"default"===c.theme||"custom"!==b&&"default"!==b||(a.head.removeChild(l),a.head.removeChild(f)),c.theme=b,"custom"===b?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):"default"!==b&&(f?f.href=J+"/vendor/themes/"+b:(f=a.createElement("link"),f.id="enhancer-for-youtube-theme-variables",f.rel="stylesheet",f.href=J+"/vendor/themes/"+b,a.head.appendChild(f)),l||(l=a.createElement("link"),l.id="enhancer-for-youtube-theme",l.rel="stylesheet",
l.href=J+"/vendor/themes/youtube-deep-dark.material.css",a.head.appendChild(l)))}catch(m){}Ua();break;case "toolbarbuttons":c.toolbarbuttons=b;k&&Ea();break;case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbarcoloractive":case "toolbaropacity":c[f.name]=b;mb();break;case "transparency":c.transparency=b;if(k)k.classList[b?"add":"remove"]("transparency");break;case "volume":c.volume=b;try{d.setVolume(b)}catch(m){}break;case "whitelist":za=""!==b?b.split(","):[];
break;case "wideplayer":c.wideplayer=b;W()&&(b?M("large"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&M("default"));break;case "wideplayerviewport":(c.wideplayerviewport=b,b)?b&&ja&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),setTimeout(function(){d&&window.scrollTo(window.scrollX,
d.getBoundingClientRect().top+window.scrollY)},80))):(a.body.classList.remove("viewport","_viewport_"),a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.scrollTo(window.scrollX,0))}});window.addEventListener("error",function(b){setTimeout(function(){q||!d||d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||a.documentElement.hasAttribute("youtube-flash-player")?3E3:1)});window.addEventListener("resize",function(a){clearTimeout(pb);
pb=setTimeout(ab,500)});var Sa;"onfullscreenchange"in a?Sa="fullscreenchange":"onmozfullscreenchange"in a&&(Sa="mozfullscreenchange");a.addEventListener(Sa,function(b){setTimeout(function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.dispatchEvent(new Event("resize"))},500)})}else if(EnhancerForYouTubePreferences.message){var l=a.createElement("link");l.rel="stylesheet";l.href=EnhancerForYouTubeResources+"/youtube-polymer.css";a.head.appendChild(l);var ha=a.createElement("div"),
Y=a.createElement("i");ha.id="page-reload-required";ha.textContent=EnhancerForYouTubeMessages.page_reload_required;Y.className="refresh";Y.addEventListener("click",function(){a.location.reload()});ha.appendChild(Y);Y=a.createElement("i");Y.className="close";Y.addEventListener("click",function(){ha.style.display="none"});ha.appendChild(Y);a.body.appendChild(ha)}})(document);